// ═══════════════════════════════════════════════════════════
// GIO RAPTOR — Code Generator
// Transforms MQL5 semantic analysis into production-ready
// TypeScript, Pine Script, Zod schemas, React config panels
// ═══════════════════════════════════════════════════════════

import type {
  SemanticAnalysis,
  GeneratedOutput,
  DeploymentManifest,
  DetectedInputParam,
  ProgramNode,
} from '@/types/converter';

function capitalize(s: string): string {
  return s.replace(/(^|[_-])(\w)/g, (_, _sep, ch) => ch.toUpperCase());
}

function camelCase(s: string): string {
  const cap = capitalize(s);
  return cap.charAt(0).toLowerCase() + cap.slice(1);
}

export class CodeGenerator {
  private analysis: SemanticAnalysis;
  private ast: ProgramNode;
  private scriptName: string;

  constructor(analysis: SemanticAnalysis, ast: ProgramNode, fileName: string) {
    this.analysis = analysis;
    this.ast = ast;
    this.scriptName = capitalize(fileName.replace(/\.(mq5|ex5)$/i, ''));
  }

  generate(): GeneratedOutput {
    return {
      typescript: this.generateTypeScript(),
      pineScript: this.generatePineScript(),
      configComponent: this.generateConfigComponent(),
      zodSchema: this.generateZodSchema(),
      testScaffold: this.generateTestScaffold(),
      deploymentManifest: this.generateDeploymentManifest(),
      documentation: this.generateDocumentation(),
      readme: this.generateReadme(),
    };
  }

  // ─── TypeScript Generation ────────────────────────────────

  private generateTypeScript(): string {
    const { scriptKind, inputParams, lifecycleHooks, indicatorBuffers } = this.analysis;
    const baseClass = scriptKind === 'indicator' ? 'GioRaptorIndicator' : 'GioRaptorEA';
    const className = this.scriptName;
    const params = inputParams;

    const lines: string[] = [
      `// ═══════════════════════════════════════════════════════════`,
      `// ${className} — Converted from MQL5 to GIO RAPTOR`,
      `// Generated by GIO RAPTOR Conversion Engine`,
      `// ═══════════════════════════════════════════════════════════`,
      ``,
      `import { ${baseClass} } from '@/lib/runtime/${scriptKind}-base';`,
      `import type { Tick, Bar, OrderRequest, Position, AccountInfo } from '@/types/trading';`,
      ``,
    ];

    // Interface for parameters
    lines.push(`export interface ${className}Params {`);
    for (const p of params) {
      lines.push(`  /** ${p.description} */`);
      lines.push(`  ${camelCase(p.name)}: ${p.tsType};`);
    }
    lines.push(`}`);
    lines.push(``);

    // Default parameters
    lines.push(`export const ${className}Defaults: ${className}Params = {`);
    for (const p of params) {
      const val = p.tsType === 'string' ? `'${p.defaultValue ?? ''}'` :
                  p.tsType === 'boolean' ? String(p.defaultValue ?? false) :
                  String(p.defaultValue ?? 0);
      lines.push(`  ${camelCase(p.name)}: ${val},`);
    }
    lines.push(`};`);
    lines.push(``);

    // Main class
    lines.push(`export class ${className} extends ${baseClass}<${className}Params> {`);

    // Indicator buffer declarations
    if (scriptKind === 'indicator' && indicatorBuffers.length > 0) {
      lines.push(`  // Indicator buffers`);
      for (const buf of indicatorBuffers) {
        lines.push(`  private ${buf.name}: number[] = [];`);
      }
      lines.push(``);
    }

    // Built-in indicator handles
    if (this.analysis.builtinIndicators.length > 0) {
      lines.push(`  // Indicator handles`);
      for (const ind of this.analysis.builtinIndicators) {
        const name = camelCase(ind.replace(/^i/, ''));
        lines.push(`  private ${name}Handle: number = -1;`);
      }
      lines.push(``);
    }

    // Constructor
    lines.push(`  constructor(params: Partial<${className}Params> = {}) {`);
    lines.push(`    super({ ...${className}Defaults, ...params });`);
    lines.push(`  }`);
    lines.push(``);

    // onInit
    if (lifecycleHooks.some(h => h.name === 'OnInit')) {
      lines.push(`  async onInit(): Promise<void> {`);
      for (const ind of this.analysis.builtinIndicators) {
        const name = camelCase(ind.replace(/^i/, ''));
        lines.push(`    this.${name}Handle = await this.createIndicator('${ind}', this.params);`);
      }
      if (indicatorBuffers.length > 0) {
        for (const buf of indicatorBuffers) {
          lines.push(`    this.registerBuffer('${buf.name}', { style: '${buf.style}', color: '${buf.color}', label: '${buf.label}' });`);
        }
      }
      lines.push(`    this.log('${className} initialized');`);
      lines.push(`  }`);
      lines.push(``);
    }

    // onTick (EA)
    if (scriptKind === 'ea' && lifecycleHooks.some(h => h.name === 'OnTick')) {
      lines.push(`  async onTick(tick: Tick): Promise<void> {`);
      lines.push(`    const positions = await this.getPositions();`);
      lines.push(`    const account = await this.getAccountInfo();`);
      lines.push(``);
      lines.push(`    // ── Signal Detection ──`);
      for (const ind of this.analysis.builtinIndicators) {
        const name = camelCase(ind.replace(/^i/, ''));
        lines.push(`    const ${name}Value = await this.getIndicatorValue(this.${name}Handle, 0);`);
      }
      lines.push(``);

      if (this.analysis.classification === 'trend_following') {
        lines.push(`    // Trend following logic`);
        lines.push(`    const buySignal = this.evaluateBuyCondition(tick);`);
        lines.push(`    const sellSignal = this.evaluateSellCondition(tick);`);
      } else if (this.analysis.classification === 'mean_reversion') {
        lines.push(`    // Mean reversion logic`);
        lines.push(`    const isOverbought = this.checkOverbought();`);
        lines.push(`    const isOversold = this.checkOversold();`);
      } else {
        lines.push(`    // Trading logic`);
        lines.push(`    const signal = this.evaluateSignal(tick);`);
      }

      lines.push(``);
      lines.push(`    // ── Order Management ──`);
      if (this.analysis.hasTrailingStop) {
        lines.push(`    await this.manageTrailingStops(positions, tick);`);
      }
      lines.push(`    await this.processSignals(tick, positions, account);`);
      lines.push(`  }`);
      lines.push(``);
    }

    // onCalculate (Indicator)
    if (scriptKind === 'indicator' && lifecycleHooks.some(h => h.name === 'OnCalculate')) {
      lines.push(`  onCalculate(bars: Bar[], prevCalculated: number): number {`);
      lines.push(`    const total = bars.length;`);
      lines.push(`    const start = prevCalculated > 0 ? prevCalculated - 1 : 0;`);
      lines.push(``);
      lines.push(`    for (let i = start; i < total; i++) {`);
      for (const buf of indicatorBuffers) {
        lines.push(`      this.${buf.name}[i] = this.calculate${capitalize(buf.name)}(bars, i);`);
      }
      lines.push(`    }`);
      lines.push(``);
      lines.push(`    return total;`);
      lines.push(`  }`);
      lines.push(``);

      // Generate calculation methods for each buffer
      for (const buf of indicatorBuffers) {
        lines.push(`  private calculate${capitalize(buf.name)}(bars: Bar[], index: number): number {`);
        lines.push(`    // Calculation logic converted from MQL5`);
        lines.push(`    return 0; // TODO: Port specific calculation`);
        lines.push(`  }`);
        lines.push(``);
      }
    }

    // onDeinit
    if (lifecycleHooks.some(h => h.name === 'OnDeinit')) {
      lines.push(`  onDeinit(): void {`);
      lines.push(`    this.log('${className} deinitialized');`);
      lines.push(`  }`);
      lines.push(``);
    }

    // Helper methods for EA
    if (scriptKind === 'ea') {
      lines.push(`  // ── Signal Evaluation ──`);
      lines.push(``);
      lines.push(`  private evaluateBuyCondition(tick: Tick): boolean {`);
      lines.push(`    // Implement buy logic from MQL5 OnTick`);
      lines.push(`    return false;`);
      lines.push(`  }`);
      lines.push(``);
      lines.push(`  private evaluateSellCondition(tick: Tick): boolean {`);
      lines.push(`    // Implement sell logic from MQL5 OnTick`);
      lines.push(`    return false;`);
      lines.push(`  }`);
      lines.push(``);
      lines.push(`  private evaluateSignal(tick: Tick): 'buy' | 'sell' | 'none' {`);
      lines.push(`    if (this.evaluateBuyCondition(tick)) return 'buy';`);
      lines.push(`    if (this.evaluateSellCondition(tick)) return 'sell';`);
      lines.push(`    return 'none';`);
      lines.push(`  }`);
      lines.push(``);
      lines.push(`  private async processSignals(tick: Tick, positions: Position[], account: AccountInfo): Promise<void> {`);
      lines.push(`    const signal = this.evaluateSignal(tick);`);
      lines.push(`    if (signal === 'none') return;`);
      lines.push(``);
      lines.push(`    const lotSize = this.calculateLotSize(account);`);
      lines.push(`    const sl = this.calculateStopLoss(tick, signal);`);
      lines.push(`    const tp = this.calculateTakeProfit(tick, signal);`);
      lines.push(``);
      lines.push(`    await this.sendOrder({`);
      lines.push(`      symbol: this.symbol,`);
      lines.push(`      type: signal === 'buy' ? 'market_buy' : 'market_sell',`);
      lines.push(`      volume: lotSize,`);
      lines.push(`      stopLoss: sl,`);
      lines.push(`      takeProfit: tp,`);
      lines.push(`      strategyId: this.strategyId,`);
      lines.push(`    });`);
      lines.push(`  }`);
      lines.push(``);
      lines.push(`  private calculateLotSize(account: AccountInfo): number {`);

      if (this.analysis.positionSizingMethod === 'risk_percent_balance') {
        lines.push(`    const riskPct = (this.params as Record<string, number>).riskPercent ?? 1;`);
        lines.push(`    return Math.max(0.01, (account.balance * riskPct / 100) / 100000);`);
      } else if (this.analysis.positionSizingMethod === 'risk_percent_equity') {
        lines.push(`    const riskPct = (this.params as Record<string, number>).riskPercent ?? 1;`);
        lines.push(`    return Math.max(0.01, (account.equity * riskPct / 100) / 100000);`);
      } else {
        const lotParam = this.analysis.inputParams.find(p =>
          p.name.toLowerCase().includes('lot') || p.name.toLowerCase().includes('volume')
        );
        lines.push(`    return ${lotParam ? `this.params.${camelCase(lotParam.name)}` : '0.01'};`);
      }

      lines.push(`  }`);
      lines.push(``);
      lines.push(`  private calculateStopLoss(tick: Tick, signal: 'buy' | 'sell'): number {`);

      const slParam = this.analysis.inputParams.find(p =>
        p.name.toLowerCase().includes('stoploss') || p.name.toLowerCase().includes('sl')
      );
      if (slParam) {
        lines.push(`    const slPoints = this.params.${camelCase(slParam.name)};`);
        lines.push(`    return signal === 'buy' ? tick.bid - slPoints * this.point : tick.ask + slPoints * this.point;`);
      } else {
        lines.push(`    return 0; // No stop loss configured`);
      }

      lines.push(`  }`);
      lines.push(``);
      lines.push(`  private calculateTakeProfit(tick: Tick, signal: 'buy' | 'sell'): number {`);

      const tpParam = this.analysis.inputParams.find(p =>
        p.name.toLowerCase().includes('takeprofit') || p.name.toLowerCase().includes('tp')
      );
      if (tpParam) {
        lines.push(`    const tpPoints = this.params.${camelCase(tpParam.name)};`);
        lines.push(`    return signal === 'buy' ? tick.bid + tpPoints * this.point : tick.ask - tpPoints * this.point;`);
      } else {
        lines.push(`    return 0; // No take profit configured`);
      }

      lines.push(`  }`);

      if (this.analysis.hasTrailingStop) {
        lines.push(``);
        lines.push(`  private async manageTrailingStops(positions: Position[], tick: Tick): Promise<void> {`);
        const tsParam = this.analysis.inputParams.find(p =>
          p.name.toLowerCase().includes('trailing')
        );
        lines.push(`    const trailPoints = ${tsParam ? `this.params.${camelCase(tsParam.name)}` : '50'};`);
        lines.push(`    for (const pos of positions) {`);
        lines.push(`      if (pos.strategyId !== this.strategyId) continue;`);
        lines.push(`      const profit = pos.type === 'buy' ? tick.bid - pos.openPrice : pos.openPrice - tick.ask;`);
        lines.push(`      if (profit > trailPoints * this.point) {`);
        lines.push(`        const newSl = pos.type === 'buy'`);
        lines.push(`          ? tick.bid - trailPoints * this.point`);
        lines.push(`          : tick.ask + trailPoints * this.point;`);
        lines.push(`        await this.modifyPosition(pos.id, { stopLoss: newSl });`);
        lines.push(`      }`);
        lines.push(`    }`);
        lines.push(`  }`);
      }
    }

    lines.push(`}`);

    return lines.join('\n');
  }

  // ─── Pine Script Generation ───────────────────────────────

  private generatePineScript(): string {
    const { scriptKind, inputParams, indicatorBuffers, builtinIndicators } = this.analysis;
    const lines: string[] = [];

    lines.push(`//@version=5`);
    if (scriptKind === 'indicator') {
      lines.push(`indicator("${this.scriptName}", overlay=true)`);
    } else {
      lines.push(`strategy("${this.scriptName}", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=1)`);
    }
    lines.push(``);

    // Input parameters
    lines.push(`// ── Parameters ──`);
    for (const p of inputParams) {
      const pineType = p.tsType === 'number' ? (String(p.defaultValue).includes('.') ? 'float' : 'int') : p.tsType;
      const defVal = p.tsType === 'string' ? `"${p.defaultValue ?? ''}"` : String(p.defaultValue ?? 0);
      lines.push(`${camelCase(p.name)} = input.${pineType}(${defVal}, title="${p.description}")`);
    }
    lines.push(``);

    // Indicator calculations
    if (builtinIndicators.length > 0) {
      lines.push(`// ── Indicators ──`);
      for (const ind of builtinIndicators) {
        const name = camelCase(ind.replace(/^i/, ''));
        switch (ind) {
          case 'iMA': {
            const periodParam = inputParams.find(p => p.name.toLowerCase().includes('period') || p.name.toLowerCase().includes('ma'));
            lines.push(`${name} = ta.sma(close, ${periodParam ? camelCase(periodParam.name) : '14'})`);
            break;
          }
          case 'iRSI': {
            const rsiPeriod = inputParams.find(p => p.name.toLowerCase().includes('rsi') || p.name.toLowerCase().includes('period'));
            lines.push(`${name} = ta.rsi(close, ${rsiPeriod ? camelCase(rsiPeriod.name) : '14'})`);
            break;
          }
          case 'iMACD': {
            lines.push(`[${name}Line, ${name}Signal, ${name}Hist] = ta.macd(close, 12, 26, 9)`);
            break;
          }
          case 'iATR':
            lines.push(`${name} = ta.atr(14)`);
            break;
          case 'iBands': {
            const bbPeriod = inputParams.find(p => p.name.toLowerCase().includes('bands') || p.name.toLowerCase().includes('bb'));
            lines.push(`[${name}Upper, ${name}Middle, ${name}Lower] = ta.bb(close, ${bbPeriod ? camelCase(bbPeriod.name) : '20'}, 2)`);
            break;
          }
          case 'iStochastic':
            lines.push(`${name}K = ta.stoch(close, high, low, 14)`);
            lines.push(`${name}D = ta.sma(${name}K, 3)`);
            break;
          case 'iADX':
            lines.push(`[${name}Plus, ${name}Minus, ${name}Value] = ta.dmi(14, 14)`);
            break;
          case 'iSAR':
            lines.push(`${name} = ta.sar(0.02, 0.02, 0.2)`);
            break;
          default:
            lines.push(`// ${ind} — manual conversion required`);
        }
      }
      lines.push(``);
    }

    // Plotting for indicators
    if (scriptKind === 'indicator') {
      lines.push(`// ── Plots ──`);
      for (const buf of indicatorBuffers) {
        lines.push(`plot(${buf.name}, title="${buf.label}", color=color.new(color.blue, 0))`);
      }
    }

    // Strategy entries for EAs
    if (scriptKind === 'ea') {
      lines.push(`// ── Strategy Logic ──`);
      lines.push(`buyCondition = false  // Port from MQL5 logic`);
      lines.push(`sellCondition = false // Port from MQL5 logic`);
      lines.push(``);
      lines.push(`if buyCondition`);
      lines.push(`    strategy.entry("Long", strategy.long)`);
      lines.push(`if sellCondition`);
      lines.push(`    strategy.entry("Short", strategy.short)`);
    }

    return lines.join('\n');
  }

  // ─── React Config Component ───────────────────────────────

  private generateConfigComponent(): string {
    const { inputParams } = this.analysis;
    const className = this.scriptName;

    const lines: string[] = [
      `'use client';`,
      ``,
      `import { useForm } from 'react-hook-form';`,
      `import { zodResolver } from '@hookform/resolvers/zod';`,
      `import { ${camelCase(className)}Schema, type ${className}Params } from './${camelCase(className)}.schema';`,
      `import { ${className}Defaults } from './${className}';`,
      ``,
      `interface ${className}ConfigProps {`,
      `  initialValues?: Partial<${className}Params>;`,
      `  onSubmit: (values: ${className}Params) => void;`,
      `  onTest?: (values: ${className}Params) => void;`,
      `}`,
      ``,
      `export function ${className}Config({ initialValues, onSubmit, onTest }: ${className}ConfigProps) {`,
      `  const { register, handleSubmit, formState: { errors }, getValues } = useForm<${className}Params>({`,
      `    resolver: zodResolver(${camelCase(className)}Schema),`,
      `    defaultValues: { ...${className}Defaults, ...initialValues },`,
      `  });`,
      ``,
      `  return (`,
      `    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">`,
      `      <div className="grid grid-cols-2 gap-4">`,
    ];

    for (const p of inputParams) {
      const fieldName = camelCase(p.name);
      if (p.tsType === 'boolean') {
        lines.push(`        <label className="flex items-center gap-2 col-span-2">`);
        lines.push(`          <input type="checkbox" {...register('${fieldName}')} className="rounded border-white/20 bg-white/5" />`);
        lines.push(`          <span className="text-sm text-white/70">${p.description}</span>`);
        lines.push(`        </label>`);
      } else {
        lines.push(`        <div>`);
        lines.push(`          <label className="block text-xs text-white/50 mb-1">${p.description}</label>`);
        lines.push(`          <input`);
        lines.push(`            type="${p.tsType === 'number' ? 'number' : 'text'}"`);
        lines.push(`            step="${p.tsType === 'number' ? '0.01' : undefined}"`);
        lines.push(`            {...register('${fieldName}'${p.tsType === 'number' ? ', { valueAsNumber: true }' : ''})}`);
        lines.push(`            className="w-full bg-white/5 border border-white/10 rounded px-3 py-2 text-sm text-white focus:border-[#00b4ff] focus:outline-none"`);
        lines.push(`          />`);
        lines.push(`          {errors.${fieldName} && <p className="text-xs text-red-400 mt-1">{errors.${fieldName}.message}</p>}`);
        lines.push(`        </div>`);
      }
    }

    lines.push(`      </div>`);
    lines.push(`      <div className="flex gap-3 pt-2">`);
    lines.push(`        <button type="submit" className="flex-1 bg-[#00b4ff] hover:bg-[#00b4ff]/80 text-white font-medium py-2 rounded transition-colors">Save Parameters</button>`);
    lines.push(`        {onTest && (`);
    lines.push(`          <button type="button" onClick={() => onTest(getValues())} className="flex-1 bg-white/5 hover:bg-white/10 text-white/70 font-medium py-2 rounded border border-white/10 transition-colors">Test Run</button>`);
    lines.push(`        )}`);
    lines.push(`      </div>`);
    lines.push(`    </form>`);
    lines.push(`  );`);
    lines.push(`}`);

    return lines.join('\n');
  }

  // ─── Zod Schema ───────────────────────────────────────────

  private generateZodSchema(): string {
    const { inputParams } = this.analysis;
    const className = this.scriptName;

    const lines: string[] = [
      `import { z } from 'zod';`,
      ``,
      `export const ${camelCase(className)}Schema = z.object({`,
    ];

    for (const p of inputParams) {
      const fieldName = camelCase(p.name);
      let zodType: string;

      if (p.tsType === 'number') {
        zodType = 'z.number()';
        if (p.min !== undefined) zodType += `.min(${p.min})`;
        if (p.max !== undefined) zodType += `.max(${p.max})`;
      } else if (p.tsType === 'boolean') {
        zodType = 'z.boolean()';
      } else {
        zodType = 'z.string()';
      }

      lines.push(`  ${fieldName}: ${zodType},`);
    }

    lines.push(`});`);
    lines.push(``);
    lines.push(`export type ${className}Params = z.infer<typeof ${camelCase(className)}Schema>;`);

    return lines.join('\n');
  }

  // ─── Test Scaffold ────────────────────────────────────────

  private generateTestScaffold(): string {
    const className = this.scriptName;
    const { scriptKind, inputParams } = this.analysis;

    return [
      `import { describe, it, expect, beforeEach } from 'vitest';`,
      `import { ${className} } from './${className}';`,
      ``,
      `describe('${className}', () => {`,
      `  let instance: ${className};`,
      ``,
      `  beforeEach(() => {`,
      `    instance = new ${className}();`,
      `  });`,
      ``,
      `  it('initializes with default parameters', () => {`,
      `    expect(instance).toBeDefined();`,
      `  });`,
      ``,
      `  it('accepts custom parameters', () => {`,
      `    const custom = new ${className}({`,
      ...inputParams.slice(0, 3).map(p => {
        const val = p.tsType === 'number' ? '10' : p.tsType === 'boolean' ? 'true' : '"test"';
        return `      ${camelCase(p.name)}: ${val},`;
      }),
      `    });`,
      `    expect(custom).toBeDefined();`,
      `  });`,
      ``,
      scriptKind === 'ea' ? [
        `  it('processes tick data without errors', async () => {`,
        `    const tick = { bid: 1.1000, ask: 1.1002, time: Date.now(), volume: 100 };`,
        `    await expect(instance.onTick(tick)).resolves.not.toThrow();`,
        `  });`,
        ``,
        `  it('evaluates signals correctly', () => {`,
        `    const tick = { bid: 1.1000, ask: 1.1002, time: Date.now(), volume: 100 };`,
        `    const signal = (instance as unknown as { evaluateSignal: (t: unknown) => string }).evaluateSignal(tick);`,
        `    expect(['buy', 'sell', 'none']).toContain(signal);`,
        `  });`,
      ].join('\n') : [
        `  it('calculates indicator values', () => {`,
        `    const bars = Array.from({ length: 100 }, (_, i) => ({`,
        `      open: 1.1 + Math.random() * 0.01,`,
        `      high: 1.11 + Math.random() * 0.01,`,
        `      low: 1.09 + Math.random() * 0.01,`,
        `      close: 1.1 + Math.random() * 0.01,`,
        `      volume: 1000,`,
        `      time: Date.now() + i * 60000,`,
        `    }));`,
        `    const result = instance.onCalculate(bars, 0);`,
        `    expect(result).toBe(100);`,
        `  });`,
      ].join('\n'),
      `});`,
    ].join('\n');
  }

  // ─── Deployment Manifest ──────────────────────────────────

  private generateDeploymentManifest(): DeploymentManifest {
    return {
      name: this.scriptName,
      version: '1.0.0',
      kind: this.analysis.scriptKind,
      classification: this.analysis.classification,
      riskFlags: this.analysis.riskFlags,
      requiredPermissions: this.getRequiredPermissions(),
      resourceLimits: {
        maxCpuMs: this.analysis.complexity === 'advanced' ? 500 : 200,
        maxMemoryMb: this.analysis.complexity === 'advanced' ? 128 : 64,
        maxApiCallsPerMinute: this.analysis.scriptKind === 'ea' ? 60 : 10,
      },
      supportedInstruments: ['*'],
      supportedTimeframes: ['M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1', 'MN1'],
      requiresBrokerApproval: this.analysis.riskFlags.length > 0 ||
        this.analysis.hasMartingale || this.analysis.hasGridLogic,
    };
  }

  private getRequiredPermissions(): string[] {
    const perms: string[] = ['read_prices', 'read_account'];
    if (this.analysis.scriptKind === 'ea') {
      perms.push('place_orders', 'modify_orders', 'close_orders');
    }
    if (this.analysis.hasNewsFilter) perms.push('read_calendar');
    if (this.analysis.multiTimeframe) perms.push('read_multi_timeframe');
    return perms;
  }

  // ─── Documentation ────────────────────────────────────────

  private generateDocumentation(): string {
    const { scriptKind, classification, inputParams, riskFlags, builtinIndicators } = this.analysis;

    return [
      `# ${this.scriptName}`,
      ``,
      `## Overview`,
      `- **Type:** ${scriptKind === 'ea' ? 'Expert Advisor' : scriptKind === 'indicator' ? 'Custom Indicator' : 'Script'}`,
      `- **Classification:** ${classification.replace(/_/g, ' ')}`,
      `- **Complexity:** ${this.analysis.complexity}`,
      `- **Converted from:** MQL5`,
      ``,
      `## Parameters`,
      `| Parameter | Type | Default | Description |`,
      `|-----------|------|---------|-------------|`,
      ...inputParams.map(p => `| ${p.name} | ${p.type} | ${p.defaultValue ?? '-'} | ${p.description} |`),
      ``,
      `## Indicators Used`,
      ...builtinIndicators.map(i => `- ${i}`),
      ``,
      riskFlags.length > 0 ? [
        `## Risk Warnings`,
        ...riskFlags.map(f => `- **${f.replace(/_/g, ' ').toUpperCase()}**`),
      ].join('\n') : '',
      ``,
      `## Trading Logic`,
      ...this.analysis.tradingLogicPatterns.map(p => `- ${p.replace(/_/g, ' ')}`),
    ].filter(Boolean).join('\n');
  }

  // ─── README ───────────────────────────────────────────────

  private generateReadme(): string {
    return [
      `# ${this.scriptName} — GIO RAPTOR Script`,
      ``,
      `Converted from MQL5 by the GIO RAPTOR Conversion Engine.`,
      ``,
      `## Quick Start`,
      ``,
      `\`\`\`typescript`,
      `import { ${this.scriptName} } from './${this.scriptName}';`,
      ``,
      `const ea = new ${this.scriptName}({`,
      ...this.analysis.inputParams.slice(0, 3).map(p => {
        const val = p.tsType === 'number' ? String(p.defaultValue ?? 0) :
                    p.tsType === 'boolean' ? String(p.defaultValue ?? false) :
                    `'${p.defaultValue ?? ''}'`;
        return `  ${camelCase(p.name)}: ${val},`;
      }),
      `});`,
      `\`\`\``,
      ``,
      `## Deployment`,
      ``,
      `Deploy via the GIO RAPTOR Converter UI or programmatically:`,
      `- **Live**: Production trading environment`,
      `- **Demo**: Demo/practice accounts only`,
      `- **Paper**: Simulated trading (no real orders)`,
      ``,
      this.analysis.riskFlags.length > 0 ? `> **Note:** This script has risk flags and requires broker approval before deployment.\n` : '',
      `## Files`,
      `- \`${this.scriptName}.ts\` — Main script class`,
      `- \`${camelCase(this.scriptName)}.schema.ts\` — Zod parameter validation`,
      `- \`${this.scriptName}Config.tsx\` — React configuration panel`,
      `- \`${this.scriptName}.pine\` — TradingView Pine Script version`,
      `- \`${this.scriptName}.test.ts\` — Test scaffold`,
    ].join('\n');
  }
}
