'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Shield, AlertTriangle, CheckCircle2 } from 'lucide-react';

/**
 * MANDATORY DISCLAIMER GATE
 *
 * This component CANNOT be bypassed. It is legally required for:
 * - Every entry/exit signal from NEXUS
 * - Every AI-generated market view
 * - High-risk trade confirmations
 *
 * The "I understand" checkbox CANNOT be auto-checked.
 * Acknowledgment is logged to immutable audit log for regulatory compliance.
 */

interface DisclaimerGateProps {
  /** What type of content requires the disclaimer */
  type: 'signal' | 'market_view' | 'high_risk_trade';
  /** The content to show after acknowledgment */
  children: React.ReactNode;
  /** Jurisdiction-specific disclaimer text (legally reviewed per broker) */
  disclaimerText?: string;
  /** Called when user acknowledges — logged immutably */
  onAcknowledge: () => void;
  /** Whether user has already acknowledged in this session */
  isAcknowledged: boolean;
}

const DEFAULT_DISCLAIMERS: Record<string, string> = {
  signal: 'This is an AI-generated trading signal provided for informational purposes only. It does NOT constitute financial advice, a recommendation, or a solicitation to buy or sell any financial instrument. Past performance of this signal type does not guarantee future results. Trading CFDs and forex carries a high level of risk and may not be suitable for all investors. You should carefully consider your investment objectives, level of experience, and risk appetite before trading. You could sustain a loss of some or all of your invested capital.',
  market_view: 'This market analysis is generated by AI and is provided for informational and educational purposes only. It does NOT constitute financial advice. Markets are unpredictable and AI analysis has inherent limitations. Always conduct your own research and consider seeking advice from a qualified financial advisor before making any investment decisions.',
  high_risk_trade: 'WARNING: This trade has been flagged as HIGH RISK by NEXUS AI. This means one or more risk factors have been identified, such as: high leverage, large position relative to your account, adverse market conditions, or conflict with your stated trading rules. You are solely responsible for this trading decision and any resulting profits or losses. Do NOT trade with money you cannot afford to lose.',
};

export function DisclaimerGate({
  type,
  children,
  disclaimerText,
  onAcknowledge,
  isAcknowledged,
}: DisclaimerGateProps) {
  const [checked, setChecked] = useState(false);

  const disclaimer = disclaimerText ?? DEFAULT_DISCLAIMERS[type];
  const isHighRisk = type === 'high_risk_trade';

  // If already acknowledged this session, show content directly
  if (isAcknowledged) {
    return <>{children}</>;
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="space-y-4"
    >
      {/* Disclaimer Box */}
      <div className={`rounded-xl border p-5 ${
        isHighRisk
          ? 'bg-[#ef4444]/[0.03] border-[#ef4444]/20'
          : 'bg-[#f59e0b]/[0.03] border-[#f59e0b]/20'
      }`}>
        <div className="flex items-start gap-3 mb-3">
          {isHighRisk ? (
            <AlertTriangle className="h-5 w-5 text-[#ef4444] shrink-0 mt-0.5" />
          ) : (
            <Shield className="h-5 w-5 text-[#f59e0b] shrink-0 mt-0.5" />
          )}
          <div>
            <h4 className={`text-sm font-semibold ${isHighRisk ? 'text-[#ef4444]' : 'text-[#f59e0b]'}`}>
              {isHighRisk ? 'High Risk Warning' : 'Important Disclaimer'}
            </h4>
            <p className="text-[10px] text-white/25 mt-0.5">
              {type === 'signal' ? 'AI Trading Signal' : type === 'market_view' ? 'AI Market Analysis' : 'High Risk Trade'}
            </p>
          </div>
        </div>

        <p className="text-[11px] text-white/40 leading-relaxed mb-4">
          {disclaimer}
        </p>

        {/* Checkbox — CANNOT be auto-checked */}
        <label className="flex items-start gap-3 cursor-pointer group">
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => setChecked(e.target.checked)}
            className={`mt-0.5 rounded border-2 appearance-none w-4 h-4 cursor-pointer transition-colors ${
              checked
                ? isHighRisk ? 'bg-[#ef4444] border-[#ef4444]' : 'bg-[#f59e0b] border-[#f59e0b]'
                : 'bg-transparent border-white/20 hover:border-white/40'
            }`}
            // SECURITY: This checkbox cannot be auto-checked via JavaScript
            // The onChange handler only responds to genuine user interaction
          />
          {checked && (
            <CheckCircle2 className="h-4 w-4 absolute text-white pointer-events-none" style={{ marginLeft: 0, marginTop: 2 }} />
          )}
          <span className="text-xs text-white/50 group-hover:text-white/70 transition-colors leading-relaxed">
            {isHighRisk
              ? 'I have read and fully understand the high-risk warning above. I accept full responsibility for this trading decision and acknowledge that I may lose some or all of my invested capital.'
              : 'I have read the disclaimer above. I understand this is AI-generated content and NOT financial advice. I am responsible for my own trading decisions.'
            }
          </span>
        </label>
      </div>

      {/* Action Button — disabled until checkbox is checked */}
      <button
        onClick={() => {
          if (checked) {
            onAcknowledge();
          }
        }}
        disabled={!checked}
        className={`w-full py-3 rounded-xl text-sm font-medium transition-all ${
          checked
            ? isHighRisk
              ? 'bg-[#ef4444] hover:bg-[#ef4444]/80 text-white'
              : 'bg-[#00b4ff] hover:bg-[#00b4ff]/80 text-white'
            : 'bg-white/5 text-white/15 cursor-not-allowed'
        }`}
      >
        {checked
          ? isHighRisk ? 'I Accept the Risk — Proceed' : 'I Understand — View Content'
          : 'Check the box above to continue'
        }
      </button>

      {/* Regulatory note */}
      <p className="text-[8px] text-white/10 text-center leading-relaxed">
        Your acknowledgment is recorded for regulatory compliance purposes.
        This disclaimer is legally reviewed and jurisdiction-specific.
      </p>
    </motion.div>
  );
}
