// ═══════════════════════════════════════════════════════════════
// EMIL EA Strategy Library — DATA. Distilled from the owner's MQL5
// Expert Advisor collection ("EA BACK UP JULY 2026"): every card was
// read from the actual .mq5 entry/exit/risk source code, not from
// marketing text. See emil-ea-knowledge.ts for how EMIL uses it.
// ═══════════════════════════════════════════════════════════════

import type { EAStrategyCard } from '@/lib/trading/emil-ea-knowledge';

export const EA_STRATEGY_CARDS: EAStrategyCard[] = [
  {
    name: "BLUEBIRD",
    family: "trend",
    indicators: ["Dual Kalman filter on close (short 50 / long 150)", "ATR(200) trend zones + SL/TP", "Kalman-state colored trend candles"],
    entry: "Two Kalman filters run over close price; trend is up when the short Kalman line is above the long. On bar close a bullish flip (short crosses above long) opens a buy, a bearish flip opens a sell. Duplicates in the same direction are skipped; OneTradeOnly blocks new trades while any position exists.",
    exit: "SL = 1.5x ATR(200), TP = 3.0x ATR at entry (either can be disabled). Optional trail moves the stop to the long-Kalman line once it is beyond the current SL. An opposite signal closes the opposing side before a new entry.",
    risk: "Risk-based lot: RiskPercent% of equity divided by SL distance (fallback fixed 0.10). One position at a time by default; no session or news filters.",
    params: ["ShortLen=50", "LongLen=150", "KalmanR=0.01", "KalmanQ=0.10", "SL=1.5xATR", "TP=3.0xATR", "RiskPercent=1.0", "UseTrail=true"],
    timeframes: ["1H", "4H"],
    pairs: [],
    edge: "A Kalman filter tracks the underlying trend with less lag and noise than moving averages, so a short/long Kalman crossover catches genuine trend changes earlier while the long line acts as dynamic trailing support.",
    terms: [
      { term: "Kalman filter", def: "A statistical smoother that estimates the 'true' price by weighing new data against its running estimate, adapting faster than a fixed-period moving average" },
      { term: "ATR (Average True Range)", def: "A volatility gauge measuring the average size of recent bars, used to size stops and targets to current conditions" },
      { term: "Trailing stop", def: "A stop loss that follows price as the trade moves into profit, locking in gains" },
      { term: "Magic number", def: "A unique ID stamped on every order so an EA only manages its own trades and ignores others on the account" },
      { term: "Bar-close trading", def: "Only evaluating signals when a candle finishes, so an entry cannot be triggered and cancelled by intra-bar wiggles" },
    ],
  },
  {
    name: "Gentleman",
    family: "trend",
    indicators: ["Fast/slow EMA crossover (auto-adaptive 8/21 M15 → 34/89 above D1)", "ADX + DI range filter", "RSI(14) confirmation", "ATR for SL/TP/trailing"],
    entry: "Bars paint green when fast EMA > slow EMA and +DI > -DI, red when inverted, gray when ADX < 20 (ranging — no trades). Buys on a flip to green (arrows additionally require RSI < 70), sells on a flip to red (RSI > 30), new-bar only. Entries blocked while gray, outside trading hours, or when spread exceeds the cap.",
    exit: "SL = 2.0x ATR, TP = 3.0x ATR at entry (TP=0 switches to signal-based exit). An ATR trailing stop (1.5x) tightens once price passes the open. CloseOnSignal exits the losing side on any opposite flip.",
    risk: "Fixed 0.01 lot or balance-risk % sizing vs SL distance. One position per direction; 30-point max-spread filter; optional server-hour window.",
    params: ["SLMult=2.0", "TPMult=3.0", "TrailATRMult=1.5", "ADXThreshold=20", "RSIPeriod=14", "MaxSpread=30", "CloseOnSignal=true"],
    timeframes: ["1H"],
    pairs: [],
    edge: "The main killer of EMA-crossover systems is whipsaw in sideways markets — gating every entry behind an ADX strength floor keeps the system flat during ranges and trades only when direction is confirmed by both EMA slope and DI dominance.",
    terms: [
      { term: "EMA (Exponential Moving Average)", def: "A moving average that weights recent prices more heavily, reacting faster to new moves than a simple average" },
      { term: "ADX", def: "Average Directional Index — measures trend strength (not direction); low readings mean the market is ranging and trend trades will chop" },
      { term: "+DI / -DI", def: "Directional indicator pair showing whether bulls or bears are in control; +DI above -DI means buying pressure dominates" },
      { term: "Whipsaw", def: "Rapid back-and-forth signals in a sideways market that repeatedly stop a trend-follower out for small losses" },
      { term: "Spread filter", def: "A rule that skips trades when the broker's bid-ask gap is too wide, protecting the edge from transaction costs" },
      { term: "RSI confirmation", def: "Using the Relative Strength Index to skip buys when already overbought (or sells when oversold)" },
    ],
  },
  {
    name: "GIOLINEREG V1",
    family: "reversal",
    indicators: ["Linear Regression Candles (LinReg(11) of OHLC)", "Signal line (SMA/EMA 11 of LinReg close)", "Optional ADX(14) + MA filters", "Swing high/low stops"],
    entry: "Builds LinReg 'candles' by fitting an 11-bar regression to each OHLC series; a candle is green when LinReg-open < LinReg-close. Default entry on trend reversal: red-to-green flip = buy, green-to-red = sell (continuation mode optional). Optional filters: LinReg close on the right side of the signal line, ADX > 20, price vs an MA.",
    exit: "SL at the 10-bar swing low/high (fallback 300 points) times the current recovery multiplier; TP = 2.0x the SL distance. An opposite signal closes everything and reverses. Optional fixed-point trailing stop (off by default).",
    risk: "Recovery system: after a loss the SL multiplier widens 1.0x → 1.5x and an entry counter increments; a win (or 5 consecutive entries) resets. Optional martingale lot scaling (1.5x, off by default); base 0.01 or risk-% sizing; one net position; spread and time filters.",
    params: ["LinRegLength=11", "SignalLength=11", "EnterOnReversal=true", "BaseSL=300", "SLMultAfterLoss=1.5", "TPRatio=2.0", "MaxEntries=5", "ScaleLots=false"],
    timeframes: ["15m", "1H"],
    pairs: [],
    edge: "Linear-regression smoothing strips candle noise so color flips mark real short-term turns; widening the stop after a loss gives the next attempt at the same turn more room to survive the noise that killed the first entry.",
    terms: [
      { term: "Linear regression", def: "A best-fit straight line through the last N prices; its endpoint is a smoothed, low-lag estimate of where price 'should' be" },
      { term: "Swing high/low", def: "The highest high or lowest low of the recent lookback window — a natural place to hide a stop beyond structure" },
      { term: "Recovery system", def: "Rules that change stop width or lot size after losses to win back drawdown, resetting after a win or a max attempt count" },
      { term: "Martingale scaling", def: "Increasing lot size after losses so one win recovers prior losses — powerful but dangerous, since losing streaks compound risk" },
      { term: "Risk:reward ratio", def: "Take-profit distance divided by stop-loss distance; 2:1 means each win pays for two losses" },
      { term: "Slippage", def: "The difference between the price you requested and the price you were actually filled at" },
    ],
  },
  {
    name: "Ichimokuthadi",
    family: "trend",
    indicators: ["Ichimoku as Donchian midpoints (auto-adaptive Tenkan/Kijun/Span A/B)", "ADX(14) adaptive range filter", "RSI(14) gate", "ATR(14) SL/TP/trail/breakeven", "Higher-TF Tenkan/Kijun alignment"],
    entry: "Classifies the market into 5 states (strong/weak bull/bear, ranging-in-cloud). Buys on a bullish Tenkan-Kijun cross or a transition to strong-bull, only if price closed above the cloud, ADX shows trending, RSI < 72 and the higher-timeframe Tenkan > Kijun. Sells are the mirror below the cloud.",
    exit: "SL/TP are ATR multiples auto-scaled by timeframe (wider for gold). Breakeven at 0.7x SL-mult ATR profit, then an ATR trail follows. A state flip against the position force-closes it regardless of SL/TP.",
    risk: "Anti-martingale: 0.01 base lot times 1.5x per consecutive win (max 5, reset on loss), always capped by 1% equity risk; lot halved in high volatility. Pauses at 10% drawdown, hardcoded news windows, optional session filter.",
    params: ["BaseLot=0.01", "LotMultiplier=1.5 (wins)", "MaxMultiplier=5", "RiskPercent=1.0", "MaxDrawdownPct=10", "RSI 72/28", "HTF=H1"],
    timeframes: ["15m", "1H", "4H"],
    pairs: ["majors", "XAUUSD", "JPY pairs"],
    edge: "Ichimoku's cloud plus TK cross gives a multi-layered trend consensus; most Ichimoku losses come from cloud-chop, so refusing all trades inside the cloud or under the ADX floor — while pyramiding size only on win streaks — keeps it aligned with strong trends.",
    terms: [
      { term: "Ichimoku cloud (Kumo)", def: "The area between Senkou Span A and B projected forward; price above the cloud is bullish territory, inside it is no-man's-land" },
      { term: "Tenkan/Kijun (TK) cross", def: "The fast conversion line crossing the slower base line — Ichimoku's classic momentum-shift trigger" },
      { term: "Donchian midpoint", def: "(Highest high + lowest low) / 2 over N bars — the formula behind every Ichimoku line" },
      { term: "Breakeven stop", def: "Moving the stop to entry once the trade has a cushion, making the worst case roughly zero" },
      { term: "Anti-martingale", def: "Increasing size after wins and resetting after losses — pressing when hot instead of doubling down when losing" },
      { term: "Drawdown pause", def: "A circuit breaker that stops new trades once equity falls a set percent below its peak" },
    ],
  },
  {
    name: "Karakattakaran",
    family: "trend",
    indicators: ["Dual Kalman filter (auto-adaptive lengths per TF)", "ADX(14) adaptive floor", "Bollinger(20,2) squeeze detector", "RSI(14) gate", "ATR(14)", "Higher-TF Kalman filter"],
    entry: "Short and long Kalman filters update on bar close; market state is bullish/bearish/ranging/transition where ranging = ADX below floor OR a Bollinger squeeze. Buys when the short Kalman crosses above the long (or state flips bullish) with no range condition, RSI < 72 and the higher-TF Kalman pair bullish. Sells mirror.",
    exit: "ATR-multiple SL/TP auto-scaled by timeframe (wider on gold). Breakeven at 0.7x SL-mult ATR, then an ATR trail every tick. A state flip against the position force-closes it.",
    risk: "Anti-martingale lot ladder (0.01 x1.5 per win, max 5, reset on loss) capped by 1% equity risk vs the ATR stop; lot halved when ATR > 2x its 50-bar average. Hard pause at 10% drawdown; news windows blocked; one position per direction.",
    params: ["KalmanR=0.01", "KalmanQ=0.10", "BaseLot=0.01", "LotMultiplier=1.5", "RiskPercent=1.0", "MaxDrawdownPct=10", "BB 20/2.0", "HTF=H1"],
    timeframes: ["15m", "1H", "4H"],
    pairs: ["all pairs", "XAUUSD"],
    edge: "A Kalman crossover reacts to real trend changes faster than moving averages; combining two independent range detectors (ADX floor + Bollinger squeeze) plus higher-timeframe alignment filters out the sideways chop where crossover systems bleed.",
    terms: [
      { term: "Kalman gain", def: "How much the filter trusts each new price versus its own estimate; controlled by the R (measurement noise) and Q (process noise) inputs" },
      { term: "Bollinger squeeze", def: "When the bands narrow sharply, signaling low volatility and a ranging market where breakout-style entries fail" },
      { term: "Higher-timeframe filter", def: "Only taking trades that agree with the trend on a slower chart, so the fast chart trades with the bigger current" },
      { term: "Position sizing by risk %", def: "Computing lot size so that hitting the stop loses a fixed percent of equity — every trade's damage is uniform" },
      { term: "Equity peak / drawdown", def: "Highest account value reached and the percent fallen from it — the standard measure of a system's pain" },
    ],
  },
  {
    name: "LinReg Candles",
    family: "trend",
    indicators: ["Linear Regression Candles (LinReg(11) of OHLC)", "Signal line (SMA/EMA 11 of LinReg close)"],
    entry: "Smooths OHLC with an 11-bar regression into synthetic candles (green when LinReg-open < LinReg-close). Buys when the last closed synthetic candle flips red-to-green OR LinReg close crosses above the signal line; sells mirror. RequireBoth demands the flip and the cross agree.",
    exit: "Fixed SL 200 points / TP 400 points (either can be disabled). An opposite signal closes and reverses (stop-and-reverse). Optional fixed-point trail, off by default.",
    risk: "Fixed 0.10 lot, no equity sizing; one net position (stop-and-reverse); 30-point spread filter; optional hour window.",
    params: ["LinRegLength=11", "SignalLength=11", "UseSMA=true", "RequireBoth=false", "SL=200pt", "TP=400pt", "MaxSpread=30"],
    timeframes: ["15m", "1H"],
    pairs: [],
    edge: "Regression-smoothed candles remove the wick noise that makes raw candle colors unreliable, so a synthetic color flip or a cross of its own smoothed average marks a cleaner short-term momentum shift.",
    terms: [
      { term: "Synthetic candles", def: "Chart candles rebuilt from transformed data (regression-fitted OHLC) instead of raw prices, making trend direction easier to read" },
      { term: "Signal line cross", def: "An entry trigger where the indicator crosses its own moving average, confirming momentum has shifted" },
      { term: "Stop-and-reverse", def: "Closing the current position and immediately opening the opposite one on an opposite signal — always in the market once running" },
      { term: "Points vs pips", def: "A point is the smallest quoted increment (often 1/10 pip on 5-digit brokers)" },
      { term: "Fixed lot sizing", def: "Trading the same volume every time regardless of account size or stop distance — simple, but risk varies with volatility" },
    ],
  },
  {
    name: "LNL GIO",
    family: "trend",
    indicators: ["L&L Trend System port: EMA(13) trend line", "EMA(8) of true range (ATR band)", "VWMA 8/13/21/34 stack", "Higher-TF stop-line replica", "Stop Line trail"],
    entry: "Watches the indicator's trend-state buffer on the last closed bar. Long when the state flips to +1 (close crosses above EMA13 + a mode-scaled ATR band); short on the -1 flip. Optional higher-TF filter requires the HTF stop-line state to agree (strict mode also demands the HTF VWMA-stack color), plus a max-spread gate.",
    exit: "Initial SL at the indicator's Stop Line; optional TP at RRRatio times the SL distance (default none). The SL trails to the current Stop Line every tick, only tightening. Opposite flips close the opposing side and reverse.",
    risk: "Fixed 0.10 lots or risk-% sizing vs SL distance. One position per direction, no martingale, 60-point spread filter.",
    params: ["Mode=NORMAL (ATR band 60-140%)", "HTFFilter=off/trend/strict", "CloseOnFlip=true", "RiskPercent=1.0", "RRRatio=0 (no TP)", "UseTrailing=true"],
    timeframes: ["1H", "4H"],
    pairs: [],
    edge: "Captures sustained directional legs by only committing once price escapes an ATR-scaled buffer around a fast EMA (filtering chop) and rides the move with a volatility-adaptive trailing stop.",
    terms: [
      { term: "Stop Line", def: "A trailing level one ATR-band below (uptrend) or above (downtrend) the EMA trend line; a close through it flips the trend state" },
      { term: "Trend flip", def: "The bar where the system's internal +1/0/-1 trend flag changes sign — the trade trigger" },
      { term: "VWMA stacking", def: "Volume-weighted MAs of lengths 8>13>21>34 lining up in order marks a cleanly bullish (or bearish) trend" },
      { term: "HTF filter", def: "Only taking signals that agree with the same calculation on a higher timeframe" },
      { term: "ATR band", def: "The buffer around the trend line sized as a percentage of ATR, controlling how easily the trend flips" },
    ],
  },
  {
    name: "Padayappa",
    family: "trend",
    indicators: ["Short Kalman (50)", "Long Kalman (150)", "ATR(200) zones and stops", "Support/resistance zones built at trend flips"],
    entry: "Crossover mode: BUY when the short Kalman crosses above the long, SELL on the opposite; an optional momentum filter requires the short Kalman to be rising for buys. Retest mode: after a bullish flip creates a support zone (flip-bar low + 0.5 ATR), buy when price dips to the zone and bounces while the trend holds; mirrored for sells.",
    exit: "SL = 1.5x ATR(200), TP = 2.0x ATR by default; retest entries anchor the SL beyond the zone edge. Optional ATR trail. With SL and TP disabled, exits happen on the opposite crossover; opposite positions always closed before entry.",
    risk: "Fixed 0.01 lot, no martingale; one position per direction; optional spread filter.",
    params: ["ShortLen=50", "LongLen=150", "SL=1.5xATR", "TP=2.0xATR", "UseRetestEntry=false", "OnlyStrongTrend=false"],
    timeframes: ["1H"],
    pairs: ["EURUSD", "XAUUSD"],
    edge: "Kalman filters smooth price with less lag than moving averages, so the crossover detects genuine turns earlier while ATR-sized zones let the retest mode buy pullbacks instead of chasing.",
    terms: [
      { term: "Crossover entry", def: "Trading the moment the fast filter line crosses the slow one, signalling a trend change" },
      { term: "Retest entry", def: "Waiting after a breakout/flip for price to come back to the new support/resistance zone and bounce before entering" },
      { term: "Support/resistance zone", def: "A price band (here the flip bar's extreme extended by half an ATR) where reactions are expected" },
      { term: "ATR-based SL/TP", def: "Stop and target distances expressed as ATR multiples so they scale with current volatility" },
    ],
  },
  {
    name: "Pattern GIO",
    family: "pattern",
    indicators: ["16 candlestick/price-action patterns (engulfing, stars, soldiers/crows, tweezers, hammer, breakouts, retest, rejection+impulsion)", "20-bar S/R zones", "EMA(50) trend filter"],
    entry: "Detects one of 16 patterns on the last closed candle — 8 bullish and 8 bearish mirrors — each validated against average body size, a 20-bar support/resistance zone and a preceding mini-trend. Bullish patterns buy only above the EMA(50), bearish sell only below; optional strong-patterns-only mode and hour window.",
    exit: "Fixed SL 30 pips, TP at 2.0R. Management every tick: breakeven+1 after +15 pips, then a 20-pip trailing stop. No opposite-signal close — trades run to SL/TP/trail.",
    risk: "1% balance risk vs SL distance (fallback 0.01), max 3 simultaneous trades, no martingale; optional 8-20h session filter.",
    params: ["RiskPercent=1.0", "SLPips=30", "RiskReward=2.0", "TrailingPips=20", "BEPips=15", "UseTrend=true (EMA50)", "MaxTrades=3"],
    timeframes: ["1H", "4H"],
    pairs: [],
    edge: "Classic candlestick reversal and breakout formations tend to resolve directionally when they appear at recent support/resistance and align with the prevailing EMA trend.",
    terms: [
      { term: "Engulfing", def: "A candle whose body completely covers the previous opposite-color body, signalling a momentum reversal" },
      { term: "Morning / Evening Star", def: "Three-bar reversal: a big candle, a tiny-bodied pause, then a big opposite candle closing past the first candle's midpoint" },
      { term: "Breakout & Retest", def: "Price breaks a prior high/low, pulls back to test the level, then resumes — a high-quality continuation pattern" },
      { term: "Tweezers", def: "Two adjacent candles with nearly identical lows (bottom) or highs (top) — the level was defended twice" },
      { term: "R (risk multiple)", def: "Profit target expressed in multiples of the stop distance; 2R means the target is twice the risked distance" },
    ],
  },
  {
    name: "SSL Hybrid",
    family: "trend",
    indicators: ["Baseline MA (HMA 60, selectable JMA/Kijun/VAMA/EDSMA…)", "Keltner-style baseline channel", "SSL1", "SSL2 (JMA 5) continuation gate", "Exit line (HMA 15)", "ATR(14, WMA-smoothed)"],
    entry: "On each closed bar: BUY when close crosses above the exit line while price is above the baseline; SELL mirrored below. With RequireSSL2 (default), the entry must pass the continuation check — price on the correct side of baseline and SSL2, with SSL2 within 0.9x ATR of price. Max-spread gate 30 points.",
    exit: "SL = 1.5x ATR, TP = 2.0x ATR. Positions force-close when close crosses the exit line against them; an opposite entry signal closes the other side first. Optional ATR trail.",
    risk: "Fixed 0.01 lot or 1% risk sizing vs the ATR stop. One position per direction, no martingale, no session filter.",
    params: ["Baseline=HMA60", "SSL2=JMA5", "Exit=HMA15", "ATRCrit=0.9", "SLMult=1.5", "TPMult=2.0", "RequireSSL2=true"],
    timeframes: ["1H", "4H", "1D"],
    pairs: [],
    edge: "The NNFX confluence idea — a slow baseline defines regime, a fast SSL2 confirms fresh momentum near price, and a mid-speed exit line times entries/exits — so trades fire only when trend, momentum and proximity all agree.",
    terms: [
      { term: "Baseline", def: "A single slow moving average that defines trend direction: only buy above it, only sell below it" },
      { term: "SSL channel", def: "Two MAs computed on highs and lows; a state flag flips when close escapes the channel" },
      { term: "Exit line", def: "A faster SSL-style line whose cross against price both triggers entries and forces exits" },
      { term: "Continuation criteria", def: "The short-term line must sit within a set ATR distance of price — proof momentum is fresh, not exhausted" },
      { term: "NNFX", def: "'No Nonsense Forex' — a method stacking a baseline, confirmation indicator and exit indicator instead of chart patterns" },
      { term: "HMA / JMA", def: "Hull and Jurik moving averages — low-lag smoothers used where a normal MA would react too slowly" },
    ],
  },
  {
    name: "SuperIchi",
    family: "trend",
    indicators: ["SuperIchi Tenkan (Supertrend-averaged, ATR 9x2)", "Kijun (ATR 26x4)", "Span A/B cloud (ATR 52x6, displaced 26)", "10-bar swing stops"],
    entry: "Rebuilds LuxAlgo's SuperIchi where each line is the midpoint of a Supertrend's tracked extremes. Fresh BUY on a Tenkan-above-Kijun cross with close above the displaced cloud; fresh SELL mirrored below. Mid-trade, a TK cross against the position — or a single opposite-color candle while TK is already against it — closes and reverses if price is on the correct cloud side.",
    exit: "SL beyond the 10-bar swing plus 50 points; TP at 2.0R. At 1R it closes 50% and moves the SL to breakeven+5. Otherwise closed/reversed on TK crosses or opposite candles.",
    risk: "Fixed 0.05 base lot (or risk-%), with explicit martingale: after each loss the next lot is x1.5 up to 5 steps, reset on a win. One position per direction; on-chart dashboard tracks win rate and drawdown.",
    params: ["BaseLot=0.05", "LotMultiplier=1.5 (5 steps)", "RiskReward=2.0", "PartialRR=1.0 @50%", "Tenkan 9x2 / Kijun 26x4 / SpanB 52x6"],
    timeframes: ["1H", "4H"],
    pairs: ["EURUSD", "XAUUSD"],
    edge: "Trades TK momentum crosses only when price is on the trend side of the cloud, using Supertrend-smoothed lines that whipsaw less than classic Ichimoku while the cloud filters counter-trend signals.",
    terms: [
      { term: "Supertrend", def: "An ATR-based trailing band; SuperIchi rebuilds Ichimoku lines as midpoints of Supertrend extremes instead of Donchian midlines" },
      { term: "Displacement", def: "The forward shift applied to the cloud, so today's price is compared against spans computed bars ago" },
      { term: "Partial close", def: "Banking a fixed percentage of the position at a milestone and moving the stop to breakeven so the runner is risk-free" },
      { term: "Martingale steps", def: "Increasing lot size after each losing trade (x1.5 up to 5 steps) to recover losses — drawdown-dangerous" },
    ],
  },
  {
    name: "SuperIchi Annamalai",
    family: "trend",
    indicators: ["SuperIchi cloud (Tenkan 9x2, Kijun 26x4, Span B 52x6, displaced 26)", "Candle color classification (green/red/gold-in-cloud)", "10-bar swing stops"],
    entry: "Classifies the last closed bar into a zone (above/below/inside the cloud) and a color. Inside the cloud it does nothing at all. A fresh green candle above the cloud opens a BUY; a fresh red candle below opens a SELL; with no positions it also enters on a steady color-plus-zone state.",
    exit: "A fresh red candle closes any BUY (then sells only below the cloud); a fresh green closes any SELL — a one-candle-color flip system. SL beyond the 10-bar swing + 50 points, TP 2.0R, 50% partial at 1R then breakeven+5.",
    risk: "Fixed 0.05 base lot or risk-%, martingale x1.5 up to 5 steps after losses, reset on a win. One position per direction; dashboard shows candle/zone state and drawdown.",
    params: ["BaseLot=0.05", "LotMultiplier=1.5", "RiskReward=2.0", "PartialRR=1.0 @50%", "SwingBars=10"],
    timeframes: ["1H"],
    pairs: ["EURUSD", "XAUUSD"],
    edge: "Uses the cloud as a hard no-trade zone and single candle-color changes as the fastest possible trend-flip trigger — in every directional run outside the cloud, flat during cloud congestion.",
    terms: [
      { term: "Gold candle", def: "A bar closing inside the cloud — treated as no-man's-land where no entries or exits are taken" },
      { term: "Cloud zone filter", def: "Only buy above the cloud, only sell below it, do nothing inside — the cloud is regime filter and chop guard" },
      { term: "Candle-color flip", def: "The first green candle after non-green (or first red after non-red) reverses the position" },
      { term: "Swing stop", def: "Placing the SL beyond the most recent N-bar extreme plus a buffer, hiding it behind market structure" },
    ],
  },
  {
    name: "Veerasamy",
    family: "trend",
    indicators: ["EMA 9/21 cross + EMA 50 filter", "ADX(14) with DI lines", "MACD(12,26,9)", "RSI(14)", "ATR(14) volatility filter", "HH/HL swing structure", "MT5 economic calendar news filter"],
    entry: "Confluence BUY when ALL hold: EMA9 > EMA21, close above EMA50, ADX >= 20 with +DI > -DI, MACD above signal, RSI 40-70, the last 1-3 candles bullish (timeframe-adaptive), and HH/HL structure confirmed; a fresh EMA9/21 up-cross with ADX/DI/MACD agreement bypasses the stricter checks. SELL mirrors. Blocked by spread, session, ATR-spike, daily-limit, drawdown and high-impact-news filters.",
    exit: "SL behind the nearest swing plus 50 points, clamped 1-3x ATR; TP at 2.0R. 50% partial at 1R, breakeven+5 after +20 points, 15-point trail after +30; closes on a bar beyond EMA21 against it or a reverse signal.",
    risk: "Fixed 0.01 lot or 1% risk sizing, optional x1.5 recovery multiplier up to 5 steps. Guards: max 3 orders, 15% max drawdown, 3% daily loss, 5 trades/3 losses per day, session filter, 30-point spread cap, news pause 30 min before to 15 min after.",
    params: ["FastEMA=9 / SlowEMA=21 / TrendEMA=50", "ADXThreshold=20", "RequireStructure=true", "RiskReward=2.0", "MaxDrawdownPct=15", "DailyLossLimit=3%", "NewsFilter=true"],
    timeframes: ["15m", "1H", "4H"],
    pairs: ["FX pairs (news filter matches currency codes)"],
    edge: "Demands agreement across trend, momentum, strength, structure and volatility filters so it only trades clean, news-quiet trending conditions, then defends profits aggressively with partials, breakeven and trailing.",
    terms: [
      { term: "Confluence", def: "Requiring several independent indicators to agree before entering — fewer but higher-quality trades" },
      { term: "Market structure (HH/HL)", def: "An uptrend defined by successive higher swing highs and higher swing lows" },
      { term: "Volatility spike filter", def: "Skipping entries when ATR exceeds 2x its recent average — abnormal bars usually mean news whips, not tradable trends" },
      { term: "News filter", def: "Automatically standing aside around high-impact economic-calendar events for the pair's currencies" },
      { term: "Daily loss limit", def: "A circuit breaker that stops new trades after a set daily loss percentage" },
    ],
  },
  {
    name: "Absolute EA",
    family: "trend",
    indicators: ["EMA 20/50/200 on M1+M5+M15", "ADX(14)", "ATR expansion vs 20-bar average", "Bollinger bandwidth", "Choppiness Index(14)", "Volume vs 20-bar MA", "SMC: order blocks, FVGs, liquidity sweeps", "50-bar S/R", "Optional US500 correlation"],
    entry: "Long only when EMAs stack bullish on M1, M5 and M15 simultaneously, structure prints HH/HL, ADX >= 25, ATR expanding > 1.1x average, no Bollinger squeeze, Choppiness < 61.8, body >= 45% of range, volume >= 1.1x average — plus optional liquidity-sweep, FVG and order-block confirmations, staying clear of S/R. Shorts mirror. A smart re-entry buys pullbacks tagging EMA20 that close back with the trend.",
    exit: "No broker TP; SL = max(1.5x ATR, 80 points). Three-tier management: at 1R close 30% and go breakeven+costs; at 2R close 30% more; at 4R close the rest — after 2R the remainder trails at ATR x 2.2.",
    risk: "1% equity risk (clamped 0.25-3.0) vs SL distance; max 3 positions; 3% daily and 8% weekly halts; 90-min cooldown after 2 losses; London/NY session filter, Friday cutoff, news-pause windows, gold/NASDAQ spread caps.",
    params: ["RiskPercent=1.0", "MinADX=25", "ATRExpansion=1.1", "MaxChoppiness=61.8", "TP tiers 1R/2R/4R (30/30/40%)", "ATRTrail=2.2", "DailyLoss=3% / WeeklyDD=8%"],
    timeframes: ["1m", "5m", "15m"],
    pairs: ["XAUUSD", "NAS100"],
    edge: "Trades only when momentum, volatility expansion and structure agree across three timeframes at once, betting that gold/NASDAQ intraday trends persist after institutional-style confirmations while heavy chop filters keep it flat in ranges.",
    terms: [
      { term: "Multi-timeframe alignment", def: "Requiring the same trend reading on several timeframes at once, so you only trade with the bigger flow" },
      { term: "ATR expansion", def: "Current volatility noticeably above its recent average — a sign a real move is starting, not drift" },
      { term: "Choppiness Index", def: "A 0-100 score of how sideways the market is; high values mean range-bound conditions where trend entries fail" },
      { term: "Liquidity sweep", def: "Price wicks through an obvious prior high/low to trigger resting stops, then closes back inside — often the launch of the real move" },
    ],
  },
  {
    name: "Bad Boy",
    family: "trend",
    indicators: ["6-EMA ribbon 8/13/21/34/55/89", "ADX(14) + DI lines", "ATR(14)", "MACD(12,26,9)"],
    entry: "Buys when the whole EMA ribbon is perfectly stacked bullish, ADX >= 20 with +DI on top, close above both EMA8 and EMA89, MACD above signal, EMA8 rising on 2 of the last 3 bars, and the ribbon width (EMA8-EMA89) is at least ATR x 0.45. Sell mirrors with a bearish stack. Once per new bar.",
    exit: "SL = ATR x 2.0, TP = ATR x 3.5 at entry; breakeven once ATR x 1.0 in profit; ATR x 1.5 trail every tick; an opposite ribbon signal force-closes and flips.",
    risk: "1% dynamic risk sizing vs SL (or fixed 0.01); max 1 open trade; optional 7-20h filter and 30-point spread cap.",
    params: ["Ribbon 8/13/21/34/55/89", "SLMult=2.0", "TPMult=3.5", "TrailMult=1.5", "ADXMin=20", "UseMACDConfirm=true", "MaxOpenTrades=1"],
    timeframes: ["15m", "1H"],
    pairs: [],
    edge: "A fully fanned-out EMA ribbon with directional ADX and MACD agreement marks strongly ordered trends; riding only those and flipping on the opposite signal avoids the whipsaw of single-MA crosses.",
    terms: [
      { term: "EMA ribbon", def: "A stack of several EMAs of increasing length; fanned out in order means a strong trend, braided together means ranging" },
      { term: "Signal flip", def: "Closing an open position and opening the opposite one when the system's signal reverses" },
      { term: "Ribbon spread check", def: "Requiring a minimum distance between the fastest and slowest EMA (in ATR units) to prove real separation, not a flat tangle" },
    ],
  },
  {
    name: "Fibonacci Bands",
    family: "reversal",
    indicators: ["SMMA(20) mid-line", "SMMA(100)-smoothed true range", "Fibonacci ATR bands at 1.618 / 2.618 / 4.236", "Pivot high/low detector", "Liquidity sweep tracker"],
    entry: "Long: while the SMMA mid-line falls, a pivot low forms below the outermost lower band and the next bar holds a higher low; this arms a sweep level, and the trade fires when a later bar wicks below that level but closes back above it (bullish sweep confirmed). Short mirrors above the outer top band. Closed bars only.",
    exit: "TP at the first inner band (38.2%); SL just beyond the outer band (50-point fallback); optionally closes early at the SMMA mid-band when in profit and price crosses back through it.",
    risk: "Fixed 0.1 lot or 1% risk sizing; max 1 position per direction; 20-point spread cap; optional 7-20h window.",
    params: ["SMMA=20", "FibRatios 1.618/2.618/4.236", "UseLiqSweep=true", "UseMidExit=true", "MaxSpread=20"],
    timeframes: ["1H", "4H"],
    pairs: ["EURUSD", "XAUUSD"],
    edge: "Prices that spike beyond an extreme volatility band (4.236x smoothed ATR) and get swept back are statistically stretched, so it fades those extremes back toward the middle of the envelope.",
    terms: [
      { term: "Volatility bands", def: "Envelopes drawn a multiple of ATR above/below a moving average; the further out, the rarer price reaches it" },
      { term: "Mean reversion", def: "Betting that an over-extended price snaps back toward its average instead of continuing" },
      { term: "Pivot high/low", def: "A bar whose extreme beats its neighbours on both sides — a confirmed local turning point" },
      { term: "SMMA", def: "Smoothed Moving Average — a slower, less jumpy average used as the band mid-line and trailing exit" },
    ],
  },
  {
    name: "Gold Scalper",
    family: "scalper",
    indicators: ["M1 EMA 8/21 crossover", "M5 EMA(50) trend + M5 EMA 8/21 alignment", "RSI(14)", "ATR(14) + 100-bar regime", "Candle body/range quality", "0-100 strength score", "Economic-calendar news filter"],
    entry: "On each closed M1 bar an EMA8/21 up-cross buys only if M5 is above its EMA50 with M5 EMAs aligned, RSI 50-70, ATR in the normal regime, M5 EMAs not compressed, and the trigger candle bullish with body >= 30% of range. A composite strength score must reach 60/100. Sells mirror with RSI 30-50. Non-repainting, one trade per signal bar.",
    exit: "SL = ATR x 1.2, TP = ATR x 1.8; 50% partial at 1R and breakeven+20 points; ATR x 1.0 trail after breakeven; optional Friday close-all.",
    risk: "0.5% risk per trade (presets 0.25/0.5/1.0); max 2 trades, 5-min cooldown; daily halts at -3%, +3% or 3 straight losses; emergency close-all at 10% drawdown; London/NY sessions only, rollover and news blackouts, 350-point spread cap.",
    params: ["Preset=BALANCED", "FastEMA=8 / SlowEMA=21", "M5TrendEMA=50", "SL=1.2xATR / TP=1.8xATR", "MinStrength=60", "DailyLoss=3% / Target=3% / MaxDD=10%"],
    timeframes: ["1m", "5m"],
    pairs: ["XAUUSD"],
    edge: "Short M1 momentum bursts on gold follow the M5 trend during London/NY liquidity; volatility-regime and strength filters skip the dead and the crazy hours that kill scalpers.",
    terms: [
      { term: "Volatility regime", def: "Classifying ATR as low/normal/abnormal and trading only 'normal' — too quiet means no follow-through, too wild means news spikes" },
      { term: "Signal strength score", def: "A 0-100 composite grading each setup so weak signals are skipped" },
      { term: "Rollover window", def: "The daily swap period around midnight server time when spreads blow out; scalpers stand aside" },
      { term: "Non-repainting", def: "Signals computed only from closed bars, so an arrow that appears never moves or disappears later" },
    ],
  },
  {
    name: "Pro Hybrid Trend Reversal",
    family: "hybrid",
    indicators: ["EMA 20/50/200 on signal TF and H1", "RSI(14)", "MACD(12,26,9)", "ATR(14)", "50-bar S/R", "Engulfing and pin-bar patterns"],
    entry: "Continuation buy: EMAs stacked bullish on both the signal TF and H1, RSI >= 52, MACD above signal. Reversal buy: a bullish engulfing or pin bar (wick > 1.8x body) closing within 8 pips of the 50-bar low. Sells mirror at resistance; a signal is voided if the opposite continuation condition is simultaneously true. One position at a time.",
    exit: "SL = ATR x 2.0 (style-adjusted) or manual 60 pips; TP = 2.0x stop distance; breakeven+2 at +30 pips; 25-pip trail; one-time 50% partial at 1.5R.",
    risk: "Fixed lot (0.01); max 1 position and 5 trades/day; spread caps 30 points FX / 50 gold; 6-22h window with per-weekday switches and Friday cutoff.",
    params: ["TradingStyle=MODERATE", "TrendConfirmTF=H1", "RiskReward=2.0", "PartialClose=50% @1.5R", "BreakEven=+30pips", "MaxTradesPerDay=5"],
    timeframes: ["1H"],
    pairs: ["FX", "XAUUSD"],
    edge: "Covers both market phases with one engine: rides established dual-timeframe momentum in trends, and in ranges fades exhaustion candlestick rejections printed right at multi-bar support/resistance.",
    terms: [
      { term: "Hybrid trend/reversal system", def: "A strategy with two independent entry paths — trend continuation and counter-trend reversal — active in both trending and ranging markets" },
      { term: "Pin bar", def: "A candle with a long rejection wick showing price probed a level and was forcefully pushed back" },
      { term: "Support/resistance buffer", def: "A small pip tolerance zone around a level; reversal patterns only count if they print inside it" },
    ],
  },
  {
    name: "SMC (Smart Money Concepts)",
    family: "pattern",
    indicators: ["Swing pivots (50-bar)", "Internal pivots (5-bar)", "BOS/CHoCH structure tracker", "Order-block registry (mitigation-aware)", "Fair-value-gap registry (ATR-thresholded)", "ATR(14) stops"],
    entry: "Three long triggers: (1) structure — close breaks a stored swing/internal pivot high, tagged BOS (trend continues) or CHoCH (trend flips); (2) order-block retest — price trades back into an active bullish OB zone; (3) FVG fill — price re-enters an unfilled bullish gap (> 0.1 ATR). Shorts mirror. Optional confluence requires internal signals to align with the swing bias.",
    exit: "SL = ATR x 1.5, TP = 2.0x SL; breakeven at 1R; optional ATR trail. OBs and FVGs are marked mitigated (dead) once price trades through them.",
    risk: "Fixed 0.10 lot or 1% risk sizing; max 2 positions; direction switches; 7-20h session filter; no martingale or grid.",
    params: ["SwingLength=50 / InternalLength=5", "UseOrderBlocks=true (lookback 5)", "UseFVG=true (0.1 ATR min)", "SL=1.5xATR / RR=2.0", "BreakEven @1R", "MaxOpenTrades=2"],
    timeframes: ["15m", "1H", "4H"],
    pairs: [],
    edge: "Trades where institutional order flow leaves footprints — structure breaks confirming a new directional leg, and retests of the origin zones (order blocks, unfilled gaps) where smart money is assumed to defend its positions.",
    terms: [
      { term: "Smart Money Concepts (SMC)", def: "A price-action framework that reads charts as the footprints of large institutional players rather than indicator math" },
      { term: "Break of Structure (BOS)", def: "Price closing beyond the most recent swing high/low in the direction of the existing trend — continuation confirmed" },
      { term: "Change of Character (CHoCH)", def: "Price breaking structure against the prevailing trend — the first warning the trend may be reversing" },
      { term: "Order block", def: "The zone of the last opposing candle(s) before a strong impulsive move; institutions are assumed to defend it on retest" },
      { term: "Fair Value Gap (FVG)", def: "A 3-candle imbalance where the middle candle moved so fast the outer candles' ranges don't overlap; price tends to return to 'fill' it" },
      { term: "Mitigation", def: "When price finally trades back through an order block or gap, 'using up' the resting orders — the zone is then spent" },
      { term: "Swing vs internal structure", def: "The same structure logic on two scales: wide pivots define the major trend, tight pivots the minor moves inside it" },
    ],
  },
  {
    name: "GIO Hull Day Trader",
    family: "trend",
    indicators: ["Donchian(20) breakout trend engine", "ATR(14, Wilder)", "Hull Suite band + arrows (visual companion)"],
    entry: "A Donchian breakout trend computed on closed bars: close above the prior 20-bar high flips the trend bullish, close below the low flips bearish. A BUY sequence opens on the bullish flip, SELL on the bearish, passing daily-limit, spread, session and news filters.",
    exit: "No stop loss — the position splits across up to 3 take-profits at 1x/2x/3x ATR (separate tickets on hedging accounts, virtual partial-closes on netting). Any opposite flip closes the losing direction (stop-and-reverse); daily profit target or loss limit force-closes everything until midnight.",
    risk: "Four lot modes (fixed 0.30, per-$1000, risk-%, balance-%); a single-step x1.5 recovery after a losing close, reset on a win. 3% daily profit target pauses trading; one sequence per direction.",
    params: ["Donchian=20", "ATR=14", "TP1/2/3=1/2/3xATR", "RecoveryMult=1.5", "DailyTarget=3%", "MaxSpread=30pt"],
    timeframes: ["15m", "1H"],
    pairs: [],
    edge: "Momentum persistence after a Donchian breakout: once price closes beyond the recent N-bar extreme it tends to keep running, so it rides each breakout leg and scales out at volatility-scaled targets.",
    terms: [
      { term: "Donchian channel", def: "The band between the highest high and lowest low of the last N bars; a close outside it signals a breakout" },
      { term: "Partial take-profit ladder", def: "Splitting one trade into portions closed at successively farther targets to bank profit while a runner rides" },
      { term: "Netting vs hedging account", def: "Netting merges all trades on a symbol into one position (TPs must be simulated by partial closes); hedging allows separate tickets each with its own TP" },
    ],
  },
  {
    name: "GIO Ichimokku",
    family: "trend",
    indicators: ["Ichimoku (Tenkan 20 / Kijun 60 / Span B 120, displacement 30)", "Kumo cloud", "TK crossover dots"],
    entry: "Signal tool (manual execution): a BUY dot prints when the Tenkan (20-bar Donchian midpoint) crosses above the Kijun (60-bar midpoint); SELL dot on the cross below. The displaced green/red cloud gives the trend backdrop. Alerts fire on the closed bar only — no repainting.",
    exit: "None coded — the implied exit is the opposite TK cross.",
    risk: "No position sizing or management — the trader executes manually off the dots and cloud.",
    params: ["Conversion=20", "Base=60", "LaggingSpan2=120", "Displacement=30"],
    timeframes: ["1H", "4H"],
    pairs: [],
    edge: "The TK cross catches momentum shifts early because both lines are range midpoints, while the displaced cloud filters which side of the structure to trade.",
    terms: [
      { term: "Tenkan-sen (Conversion Line)", def: "Midpoint of the highest high and lowest low of the last N bars — the fast Ichimoku line" },
      { term: "Kijun-sen (Base Line)", def: "Midpoint of a longer range — the slow equilibrium line; price far from it tends to snap back" },
      { term: "Senkou Span A / B", def: "Leading lines (Tenkan/Kijun average and long-range midpoint) plotted forward to form the cloud" },
    ],
  },
  {
    name: "Trendinator",
    family: "trend",
    indicators: ["ADX/DMI(14)", "EMA 12 & 50", "Squeeze Momentum (Bollinger 20/2 inside Keltner 20/1.5)", "Volume-trend histogram", "Dashboard + bar coloring"],
    entry: "Signal tool: BUY arrow when +DI crosses above -DI, SELL on the reverse, alerted on the closed bar. The dashboard prints STRONG BUY only when EMA12 > EMA50, +DI > -DI AND ADX > 20 (mirror for STRONG SELL); candles recolor gold when ADX is under threshold — no-trade chop.",
    exit: "None coded — the implied exit is the opposite DI cross or ADX falling under 20. The squeeze release and volume spikes act as discretionary cues.",
    risk: "No trade management — a filter/confirmation tool meant to keep the trader out of ranging markets.",
    params: ["ADXPeriod=14", "ADXThreshold=20", "EMAFast=12 / EMASlow=50", "Squeeze BB 20/2 vs KC 20/1.5"],
    timeframes: ["15m", "1H", "4H"],
    pairs: [],
    edge: "Trend-following signals only pay when a trend actually exists — ADX above 20 with DI alignment filters out the ranging conditions where crossover systems bleed.",
    terms: [
      { term: "Squeeze (BB inside KC)", def: "When Bollinger Bands contract inside the Keltner Channel, volatility is coiling; the squeeze 'firing' often precedes an explosive move" },
      { term: "Keltner Channel", def: "An ATR-based envelope around a moving average — wider in volatile markets" },
      { term: "EMA trend filter", def: "Fast EMA above slow EMA = bullish bias; only taking signals that agree with this backdrop cuts counter-trend losers" },
    ],
  },
  {
    name: "XAU Trend Range Avoidance",
    family: "trend",
    indicators: ["EMA 20/50/200 on M1/M5/M15", "ADX(14) per TF", "ATR(14) per TF", "Bollinger(20,2) width vs ATR", "Multi-TF trend/range panel"],
    entry: "Each of M1/M5/M15 is 'ranging' (no trade) if ADX < 22, ATR < 120 points, or BB-width/ATR < 1.20. To trade, none may be ranging, M5 and M15 trends must agree (EMA 20>50>200 with close above EMA20, or mirror), and the M1 trigger is a fresh close back across EMA20 in the trend direction.",
    exit: "SL = 1.6x M1 ATR, TP = 2.4x M1 ATR at entry. Breakeven+20 points after +1.0 ATR; beyond 1.2 ATR profit the SL trails at 1.2x ATR. No reversal exit.",
    risk: "1% risk sizing vs the ATR stop (fixed 0.01 optional); max 1 position, 3-bar cooldown, 80-point spread cap, optional 6-23h filter. No martingale.",
    params: ["MinADX=22", "MinATR=120pt", "MinBBWidthATR=1.20", "SL=1.6xATR / TP=2.4xATR", "BreakEvenAfter=1.0ATR", "Trail=1.2xATR", "Cooldown=3 bars"],
    timeframes: ["1m", "5m", "15m"],
    pairs: ["XAUUSD"],
    edge: "Gold trends hard but chops harder — requiring stacked EMAs on two higher timeframes plus a triple volatility/strength gate (ADX, ATR floor, BB expansion) keeps it flat during consolidation and active only when a real impulse is underway.",
    terms: [
      { term: "EMA stack", def: "Fast > slow > long-term EMA in order (20>50>200) — the classic definition of an established trend" },
      { term: "Range / consolidation filter", def: "Rules that detect sideways markets (weak ADX, small ATR, narrow Bollinger width) and block entries there" },
      { term: "Bollinger Band width", def: "Distance between the bands divided by ATR — a low ratio means compression: breakout-prone but trend-hostile" },
    ],
  },
  {
    name: "GIO Hull Pro Scalper",
    family: "scalper",
    indicators: ["Hull Suite (HMA/EHMA/THMA, length 55)", "Donchian(20) trend ribbon", "M5 Hull higher-TF filter", "Swing high/low stops"],
    entry: "On the last closed M1 bar: BUY when the Hull line crosses above its value 2 bars back AND the Donchian trend ribbon is green AND (if enabled) the M5 Hull trend is up; SELL mirrors with a red ribbon. One position at a time, one signal per bar.",
    exit: "SL at the 10-bar swing plus a 20-point buffer, defining R. The position splits into 5 equal parts taken at 1R through 5R via partial closes; after the first partial the SL moves to breakeven. An opposite Hull+ribbon signal closes the remainder.",
    risk: "Base 0.01 lot or risk-% vs the swing stop; martingale x1.5 per loss streak up to 5 steps, then reset. A 5% daily profit target halts new trades for the day.",
    params: ["HullMode=HMA len 55", "Donchian=20", "HtfTF=M5", "SwingLookback=10 +20pt", "NumTP=5 (1R-5R)", "MartingaleMult=1.5 (5 steps)", "DailyTarget=5%"],
    timeframes: ["1m", "5m"],
    pairs: ["majors", "XAUUSD"],
    edge: "A low-lag Hull turn firing in the same direction as a fresh Donchian breakout and the M5 trend catches short intraday momentum bursts, which the 1R-5R ladder milks while breakeven protection caps the give-back.",
    terms: [
      { term: "Hull Suite (HMA/EHMA/THMA)", def: "Three Hull moving average variants — ultra-low-lag averages whose slope/cross flags trend turns almost in real time" },
      { term: "Donchian trend ribbon", def: "A trend state from Donchian breakouts: green after a close above the channel high, red after a close below the low, held until the opposite break" },
      { term: "R-multiple ladder", def: "Take-profits at 1 to 5 times the stop distance, banking progressively as the move extends" },
    ],
  },
  {
    name: "GIO Kalman Trend System",
    family: "trend",
    indicators: ["Short Kalman line (50)", "Long Kalman line (150)", "Crossover arrows / trend buffer via iCustom"],
    entry: "Entry 1: BUY when the short Kalman crosses above the long on a closed bar; SELL on the opposite — any opposite cycle is closed first. Entry 2 (add-on, same lot): during an active cycle, when a pullback touches the short Kalman line, one retracement entry is added, once per cycle.",
    exit: "No SL and no TP — exits are purely signal-based: the opposite crossover closes BOTH cycle positions and arms the reverse cycle (stop-and-reverse). New-bar-only, duplicate-cross suppression, hours window and spread gate.",
    risk: "Initial 0.01 lot (or auto by balance); per-cycle recovery: after a net-losing cycle the next cycle's lot is base x 1.5^level (capped at 6), reset after a winning cycle. Max 2 positions per cycle; state persists across restarts via global variables.",
    params: ["ShortLen=50", "LongLen=150", "R=0.01 / Q=0.10", "Multiplier=1.5 (max level 6)", "MaxSpread=50pt", "TradeNewBarOnly=true"],
    timeframes: ["15m", "1H", "4H"],
    pairs: [],
    edge: "Kalman filters smooth price optimally against noise with minimal lag, so the fast/slow crossover flags regime changes earlier than equivalent moving averages, and the pullback-to-fast-line add-on buys the trend at a discount.",
    terms: [
      { term: "Process noise (Q) / measurement noise (R)", def: "The Kalman filter's two tuning knobs: higher Q reacts faster to real moves; higher R distrusts noisy ticks and smooths more" },
      { term: "Trading cycle", def: "The full life of one directional idea — entry, optional add-on, exit on the opposite signal — with P/L accounted per cycle" },
      { term: "Retracement add-on", def: "Adding a second position when price pulls back to the fast line inside an established trend, improving average entry" },
      { term: "Signal-based exit", def: "Closing only when the indicator flips rather than at a fixed stop — risk is managed by the reversal signal and position sizing" },
    ],
  },
];
