export type NewsCategory = 'forex' | 'crypto' | 'commodities' | 'indices' | 'central-banks';
export type NewsImpact = 'high' | 'medium' | 'low';

export interface NewsItem {
  id: string;
  headline: string;
  summary: string;
  fullContent: string;
  source: string;
  category: NewsCategory;
  impact: NewsImpact;
  currencies: string[];
  timestamp: Date;
}

export function generateNewsItems(): NewsItem[] {
  const now = Date.now();
  const minAgo = (m: number) => new Date(now - m * 60000);

  const items: NewsItem[] = [
    {
      id: 'n1',
      headline: 'Fed Signals Potential Rate Cut in June Meeting Minutes',
      summary: 'Federal Reserve officials discussed the possibility of easing monetary policy as early as June, citing slowing inflation data and softening labor market conditions.',
      fullContent: 'Federal Reserve officials discussed the possibility of easing monetary policy as early as June, according to meeting minutes released today. Several FOMC members noted that inflation data had been trending favorably toward the 2% target, while labor market indicators showed signs of gradual cooling. The minutes revealed a growing consensus that the restrictive policy stance may need adjustment sooner than previously anticipated. Markets immediately priced in a 78% probability of a 25 basis point cut at the June meeting, up from 55% before the release. The dollar index weakened across the board following the release.',
      source: 'Reuters',
      category: 'central-banks',
      impact: 'high',
      currencies: ['USD', 'EUR', 'GBP'],
      timestamp: minAgo(12),
    },
    {
      id: 'n2',
      headline: 'Gold Surges Past $2,400 on Geopolitical Tensions',
      summary: 'Spot gold breaks above $2,400 per ounce for the first time as investors flock to safe-haven assets amid escalating Middle East tensions and weakening dollar.',
      fullContent: 'Gold prices surged past $2,400 per ounce in early Asian trading, reaching new all-time highs as a combination of geopolitical tensions and expectations of US rate cuts drove investor demand. The precious metal gained 2.3% in the session, with physical buying accelerating across Asian markets. Central bank purchases continue to provide structural support, with China and India leading accumulation. Technical analysts noted the breakout above the previous resistance at $2,380 opens the path toward $2,500.',
      source: 'Bloomberg',
      category: 'commodities',
      impact: 'high',
      currencies: ['XAU', 'USD'],
      timestamp: minAgo(35),
    },
    {
      id: 'n3',
      headline: 'Bitcoin Breaks $70K as ETF Inflows Accelerate',
      summary: 'Bitcoin surpasses the $70,000 level as institutional ETF inflows reach $1.2 billion this week, signaling renewed risk appetite among institutional investors.',
      fullContent: 'Bitcoin has broken above the $70,000 psychological level, propelled by massive inflows into US-listed spot Bitcoin ETFs. Weekly inflows reached $1.2 billion, the highest since the initial launch period. BlackRock IBIT led the inflows with $540 million, followed by Fidelity FBTC with $320 million. The rally comes amid broader risk-on sentiment as equities also trade near record highs. Analysts suggest the next major resistance sits at $73,800, the previous all-time high.',
      source: 'CNBC',
      category: 'crypto',
      impact: 'high',
      currencies: ['BTC', 'USD'],
      timestamp: minAgo(58),
    },
    {
      id: 'n4',
      headline: 'EUR/USD Drops After Weak Eurozone PMI Data',
      summary: 'The euro tumbles 60 pips against the dollar after flash PMI readings show manufacturing contraction deepening across Germany and France.',
      fullContent: 'EUR/USD fell sharply from 1.0920 to 1.0860 following disappointing Eurozone flash PMI data. German manufacturing PMI came in at 42.2 versus 43.1 expected, while French manufacturing surprised to the downside at 44.1 versus 46.0 consensus. The services sector offered limited consolation with the composite reading falling to 50.3 from 50.8. ECB rate cut expectations for the April meeting rose to 85% from 70% as the data strengthened the case for monetary easing.',
      source: 'FXStreet',
      category: 'forex',
      impact: 'high',
      currencies: ['EUR', 'USD'],
      timestamp: minAgo(92),
    },
    {
      id: 'n5',
      headline: 'Bank of Japan Hints at Policy Shift, Yen Strengthens',
      summary: 'BOJ Governor signals readiness to raise rates further if inflation remains above target, sending USD/JPY down 150 pips in volatile trading.',
      fullContent: 'The Japanese yen strengthened significantly after Bank of Japan Governor indicated in a parliamentary testimony that additional rate increases remain on the table. USD/JPY dropped from 152.80 to 151.30 in the aftermath, with the move accelerating as technical stops were triggered below 152.00. The Governor cited sustained wage growth and persistent service sector inflation as factors supporting further normalization. Japanese government bond yields rose across the curve, with the 10-year reaching 1.08%.',
      source: 'Reuters',
      category: 'central-banks',
      impact: 'high',
      currencies: ['JPY', 'USD'],
      timestamp: minAgo(128),
    },
    {
      id: 'n6',
      headline: 'UK Inflation Surprises Higher, BoE Cut Delayed',
      summary: 'British CPI comes in at 3.4% versus 3.2% expected, reducing chances of a Bank of England rate cut in May and boosting the pound.',
      fullContent: 'UK Consumer Price Index rose 3.4% year-over-year in the latest reading, exceeding the 3.2% forecast and the previous 3.2% figure. Core CPI also surprised higher at 4.5% versus 4.3% expected. The data prompted a reassessment of Bank of England rate cut timing, with May cut probability dropping to 15% from 40%. GBP/USD jumped 45 pips on the release, testing the 1.2700 level. Services inflation remained sticky at 6.1%, a key metric watched by the MPC.',
      source: 'Bloomberg',
      category: 'forex',
      impact: 'high',
      currencies: ['GBP', 'USD'],
      timestamp: minAgo(165),
    },
    {
      id: 'n7',
      headline: 'Crude Oil Rallies on OPEC+ Production Cut Extension',
      summary: 'WTI crude jumps 3.2% to $82.50 after OPEC+ agrees to extend voluntary production cuts through Q3, tightening supply outlook.',
      fullContent: 'Oil prices surged after OPEC+ members agreed to extend voluntary production cuts of 2.2 million barrels per day through the third quarter of 2024. WTI crude rose 3.2% to $82.50 per barrel while Brent gained 2.8% to $86.70. Saudi Arabia will maintain its additional voluntary cut of 1 million bpd. The decision was widely expected but the extension through Q3 exceeded some analyst forecasts for a Q2-only extension. Energy stocks rallied in sympathy with the Stoxx Europe 600 Energy index gaining 2.1%.',
      source: 'Reuters',
      category: 'commodities',
      impact: 'medium',
      currencies: ['USD', 'CAD'],
      timestamp: minAgo(210),
    },
    {
      id: 'n8',
      headline: 'S&P 500 Hits Record High on Tech Earnings Beat',
      summary: 'US equities rally to fresh all-time highs as mega-cap tech companies report better-than-expected quarterly earnings and robust guidance.',
      fullContent: 'The S&P 500 closed at a new record high of 5,320, gaining 1.4% on the session as major technology companies delivered strong quarterly results. The tech-heavy Nasdaq Composite rose 1.8% while the Dow Jones added 280 points. Semiconductor stocks led the advance with the SOX index up 3.2%. Risk appetite improved broadly, with the VIX falling below 13 for the first time in two weeks. The rally was supported by strong earnings growth in the AI-related segment, with several companies raising full-year guidance.',
      source: 'CNBC',
      category: 'indices',
      impact: 'medium',
      currencies: ['USD'],
      timestamp: minAgo(255),
    },
    {
      id: 'n9',
      headline: 'AUD/USD Jumps as RBA Holds Rates, Signals Hawkish Stance',
      summary: 'Australian dollar gains after RBA keeps cash rate at 4.35% and Governor Bullock warns against premature rate cut expectations.',
      fullContent: 'The Australian dollar surged to a two-week high against the greenback after the Reserve Bank of Australia held interest rates steady at 4.35% and delivered a notably hawkish statement. RBA Governor Bullock emphasized that inflation remains too high and the board is not ruling out further tightening. AUD/USD jumped from 0.6540 to 0.6590 following the decision. Rate cut expectations for the first easing were pushed back from August to November. Australian government bond yields rose 8-12 basis points across the curve.',
      source: 'Bloomberg',
      category: 'central-banks',
      impact: 'high',
      currencies: ['AUD', 'USD'],
      timestamp: minAgo(310),
    },
    {
      id: 'n10',
      headline: 'Swiss Franc Weakens After SNB Surprise Rate Cut',
      summary: 'The Swiss National Bank unexpectedly cuts rates by 25bps to 1.50%, catching markets off guard and sending EUR/CHF to three-month highs.',
      fullContent: 'In a surprise move, the Swiss National Bank cut its policy rate by 25 basis points to 1.50%, becoming the first major central bank to begin easing. Only 15% of surveyed economists expected the cut. EUR/CHF jumped 80 pips to 0.9740 while USD/CHF rallied to 0.8950. SNB Chairman cited the sustained appreciation of the Swiss franc and below-target inflation as key reasons for the decision. Swiss inflation has been running below the 0-2% target band for several months.',
      source: 'FXStreet',
      category: 'central-banks',
      impact: 'high',
      currencies: ['CHF', 'EUR'],
      timestamp: minAgo(380),
    },
    {
      id: 'n11',
      headline: 'Ethereum Breaks $3,500 as Network Upgrade Approaches',
      summary: 'ETH rallies 8% as developers confirm the Dencun upgrade is on track, expected to significantly reduce Layer 2 transaction costs.',
      fullContent: 'Ethereum surged past the $3,500 level in a broad crypto rally, with the upcoming Dencun network upgrade providing a fundamental catalyst. The upgrade promises to reduce Layer 2 transaction fees by up to 90% through the introduction of proto-danksharding. ETH/BTC also strengthened, gaining 3% as capital rotated from Bitcoin into altcoins. Open interest in ETH futures reached record levels at $12.5 billion, suggesting strong institutional participation in the move.',
      source: 'CNBC',
      category: 'crypto',
      impact: 'medium',
      currencies: ['ETH', 'BTC'],
      timestamp: minAgo(420),
    },
    {
      id: 'n12',
      headline: 'Canadian Employment Surges, Loonie Rallies',
      summary: 'Canada adds 41,400 jobs in March versus 25,000 expected, unemployment holds at 6.1%, reducing odds of near-term BoC rate cut.',
      fullContent: 'Statistics Canada reported a much stronger-than-expected employment gain of 41,400 jobs in March, well above the consensus estimate of 25,000. The unemployment rate held steady at 6.1% instead of rising to 6.2% as forecast. Full-time employment accounted for the bulk of gains at 35,200. Average hourly wages rose 5.1% year-over-year, above expectations. USD/CAD fell 50 pips to 1.3540 following the release as markets reduced Bank of Canada rate cut bets. The probability of an April cut dropped from 45% to 25%.',
      source: 'Reuters',
      category: 'forex',
      impact: 'high',
      currencies: ['CAD', 'USD'],
      timestamp: minAgo(480),
    },
    {
      id: 'n13',
      headline: 'China PMI Returns to Expansion, Risk Appetite Improves',
      summary: 'Official Chinese manufacturing PMI rises to 50.8, the first expansion in six months, boosting commodity currencies and Asian equities.',
      fullContent: 'China official manufacturing PMI rose to 50.8 in March from 49.1 in February, crossing above the 50 expansion-contraction threshold for the first time since September. New orders and production sub-indices both improved significantly. The data suggests fiscal stimulus measures are beginning to gain traction. AUD and NZD rallied on the news given their sensitivity to Chinese economic activity. Copper prices rose 1.5% while iron ore gained 2.3%. The Hang Seng index jumped 2.1% in early trading.',
      source: 'Bloomberg',
      category: 'indices',
      impact: 'medium',
      currencies: ['CNY', 'AUD', 'NZD'],
      timestamp: minAgo(540),
    },
    {
      id: 'n14',
      headline: 'NZD/USD Falls on Dovish RBNZ Commentary',
      summary: 'New Zealand dollar weakens after RBNZ Assistant Governor suggests restrictive policy is working faster than expected on inflation.',
      fullContent: 'The New Zealand dollar dropped 40 pips against the US dollar after comments from RBNZ Assistant Governor suggesting the central bank is increasingly confident that monetary policy is sufficiently restrictive. NZD/USD fell from 0.6080 to 0.6040 as markets interpreted the remarks as opening the door for earlier rate cuts. Two-year swap rates fell 7 basis points as rate cut expectations were brought forward. The RBNZ next meets on May 22, with markets now pricing a 60% chance of a cut.',
      source: 'FXStreet',
      category: 'forex',
      impact: 'medium',
      currencies: ['NZD', 'USD'],
      timestamp: minAgo(600),
    },
    {
      id: 'n15',
      headline: 'Silver Breaks Multi-Year Resistance on Industrial Demand',
      summary: 'Silver spot prices jump 4% to $28.50 as solar panel demand forecasts are revised higher, adding to monetary demand from rate cut expectations.',
      fullContent: 'Silver prices broke through the $28 resistance level that had capped gains since 2021, reaching $28.50 in a 4% intraday rally. The move was driven by revised solar panel demand forecasts from the International Energy Agency, which increased its 2024 estimate by 15%. Silver industrial demand from the photovoltaic sector is expected to consume 20% of annual mine supply. The rally was amplified by the weakness in the US dollar and falling real yields. Gold-silver ratio dropped below 84, suggesting silver may continue to outperform.',
      source: 'Reuters',
      category: 'commodities',
      impact: 'medium',
      currencies: ['XAG', 'USD'],
      timestamp: minAgo(670),
    },
    {
      id: 'n16',
      headline: 'US Retail Sales Beat Expectations, Dollar Recovers',
      summary: 'March retail sales rise 0.7% m/m vs 0.4% expected, suggesting the US consumer remains resilient despite higher interest rates.',
      fullContent: 'US retail sales rose 0.7% month-over-month in March, significantly beating the 0.4% consensus estimate. The control group, which feeds directly into GDP calculations, also surprised higher at 1.1% vs 0.4% expected. The dollar index recovered 0.3% on the release as the strong consumption data pushed back rate cut expectations slightly. USD/JPY bounced 30 pips while EUR/USD dipped. The data suggests Q1 GDP tracking estimates may be revised higher. Treasury yields rose 5-8 bps across the curve.',
      source: 'CNBC',
      category: 'forex',
      impact: 'high',
      currencies: ['USD'],
      timestamp: minAgo(740),
    },
    {
      id: 'n17',
      headline: 'ECB Lagarde Signals Rate Cut Path Starting June',
      summary: 'ECB President Lagarde confirms June as the likely start of rate cuts if disinflation process continues, EUR weakens across the board.',
      fullContent: 'ECB President Christine Lagarde provided the clearest signal yet that the European Central Bank will begin cutting interest rates in June. Speaking at a press conference in Frankfurt, Lagarde stated the Governing Council would have sufficient data by June to assess whether the disinflation process is sustainably on track. EUR/USD fell 30 pips to 1.0850 on the comments. Short-term European rates fell as markets moved to fully price a 25bp June cut. The euro weakened against all major peers, with EUR/GBP falling to 0.8530.',
      source: 'Bloomberg',
      category: 'central-banks',
      impact: 'high',
      currencies: ['EUR', 'USD', 'GBP'],
      timestamp: minAgo(830),
    },
    {
      id: 'n18',
      headline: 'Nikkei 225 Reaches 40-Year High on Weak Yen',
      summary: 'Japanese benchmark index surpasses 41,000 as the weak yen continues to boost exporter earnings and foreign investor flows accelerate.',
      fullContent: 'The Nikkei 225 broke above 41,000 for the first time since 1989, extending its remarkable rally driven by yen weakness and corporate governance reforms. The index has gained 18% year-to-date as the depreciated yen inflates overseas earnings for major exporters. Foreign investors have been net buyers for 12 consecutive weeks. Toyota, Sony, and semiconductor equipment makers led the advance. The Bank of Japan policy divergence with other central banks continues to provide a tailwind for Japanese equities even as it weighs on the currency.',
      source: 'Reuters',
      category: 'indices',
      impact: 'medium',
      currencies: ['JPY'],
      timestamp: minAgo(900),
    },
    {
      id: 'n19',
      headline: 'GBP/JPY Hits 8-Year High on Yield Differential',
      summary: 'Sterling reaches 193.50 against the yen as the wide interest rate gap between the UK and Japan drives carry trade flows.',
      fullContent: 'GBP/JPY surged to 193.50, the highest level since 2016, as the significant yield differential between UK and Japanese bonds continued to attract carry trade flows. With the BOE holding rates at 5.25% versus the BOJ at 0.10%, the 515bp gap makes the trade highly attractive for leveraged investors. The pair has gained 5% this quarter. However, analysts warn that a potential BOJ intervention or unexpected policy shift could trigger a sharp reversal. Japanese officials reiterated they are watching currency moves with vigilance.',
      source: 'FXStreet',
      category: 'forex',
      impact: 'medium',
      currencies: ['GBP', 'JPY'],
      timestamp: minAgo(980),
    },
    {
      id: 'n20',
      headline: 'Natural Gas Drops 5% on Mild Weather Forecasts',
      summary: 'US natural gas futures tumble as extended weather models show above-normal temperatures across the Northeast, reducing heating demand outlook.',
      fullContent: 'US natural gas futures dropped 5% to $1.75/MMBtu as the latest 11-16 day weather forecasts showed above-normal temperatures persisting across the key Northeast demand region. Storage levels remain 21% above the five-year average, adding to bearish pressure. European TTF gas also fell 3% in sympathy. The mild weather outlook comes as US production remains near record levels at 103 Bcf/d. LNG export nominations were steady but failed to provide sufficient support. Technical analysts noted the break below $1.80 opens downside risk toward the contract low at $1.52.',
      source: 'Bloomberg',
      category: 'commodities',
      impact: 'low',
      currencies: ['USD'],
      timestamp: minAgo(1050),
    },
    {
      id: 'n21',
      headline: 'Solana Outperforms as DEX Volume Hits Record',
      summary: 'SOL gains 12% as decentralized exchange volume on the Solana network reaches $3.8 billion daily, surpassing Ethereum for the first time.',
      fullContent: 'Solana token surged 12% to $185 as on-chain metrics showed decentralized exchange trading volume on the network hitting $3.8 billion in a single day, overtaking Ethereum for the first time. The milestone highlights the growing adoption of Solana as a DeFi hub, driven by lower fees and faster transaction speeds. Total value locked on Solana DeFi protocols rose to $5.2 billion. The rally extended to the broader Solana ecosystem with meme tokens and gaming tokens posting double-digit gains.',
      source: 'CNBC',
      category: 'crypto',
      impact: 'medium',
      currencies: ['SOL', 'ETH'],
      timestamp: minAgo(1120),
    },
    {
      id: 'n22',
      headline: 'US 10-Year Yield Falls Below 4.2% on Weak Payrolls Revision',
      summary: 'Treasury benchmark yield drops to 4.18% after BLS revises prior months NFP data down by 71K, suggesting softer labor market conditions.',
      fullContent: 'The US 10-year Treasury yield fell below 4.2% for the first time in two weeks after the Bureau of Labor Statistics revised down nonfarm payroll figures for the prior two months by a combined 71,000 jobs. The revision suggests the labor market has been cooling more than initially reported. The 2-year yield also declined 10bps to 4.55%, steepening the yield curve slightly. Rate-sensitive sectors of the equity market rallied, with REITs and utilities outperforming. Fed funds futures moved to price in two full rate cuts by year-end.',
      source: 'Reuters',
      category: 'forex',
      impact: 'high',
      currencies: ['USD'],
      timestamp: minAgo(1200),
    },
    {
      id: 'n23',
      headline: 'EUR/GBP Drops to 7-Month Low on Diverging Data',
      summary: 'The euro falls against sterling as Eurozone data disappoints while UK services PMI beats expectations, widening the growth differential.',
      fullContent: 'EUR/GBP fell to its lowest level in seven months at 0.8505, driven by a widening growth gap between the Eurozone and the UK. UK services PMI came in at 54.9 versus 53.5 expected, while Eurozone services PMI missed at 51.1 versus 52.0 forecast. The divergence in economic performance has led markets to expect the ECB to cut rates before the BoE. Rate swap markets now price in 100bp of ECB cuts versus only 50bp for the BoE by year-end. The pair broke below the key 0.8520 support level, opening the path toward 0.8470.',
      source: 'FXStreet',
      category: 'forex',
      impact: 'medium',
      currencies: ['EUR', 'GBP'],
      timestamp: minAgo(1330),
    },
  ];

  return items;
}

export const SOURCE_COLORS: Record<string, string> = {
  Reuters: '#F97316',
  Bloomberg: '#8B5CF6',
  CNBC: '#3B82F6',
  FXStreet: '#22C55E',
};
